import { useState } from 'react'
import { Button, EmptyState, Icon } from '../../ds'
import type { LocalStoryArc } from '../../local/types'
import { Editor, type SectionProps } from './shared'

const ARC_COLUMNS: Array<{ status: LocalStoryArc['status']; label: string; hint: string }> = [
  { status: 'planned', label: 'Замысел', hint: 'Линии, которые ещё не вышли на сцену' },
  { status: 'active', label: 'В игре', hint: 'То, что прямо сейчас меняет мир' },
  { status: 'resolved', label: 'Завершено', hint: 'Линии с зафиксированным исходом' },
]

type Draft = Omit<LocalStoryArc, 'id'>
const EMPTY: Draft = { title: '', direction: '', stakes: '', status: 'planned', progress: 0, owner: '', mode: 'foreground' }

export function ArcsSection({ campaign, persist }: SectionProps) {
  const arcs = campaign.storyArcs
  const [editor, setEditor] = useState<LocalStoryArc | 'new' | null>(null)
  const [draft, setDraft] = useState<Draft>(EMPTY)
  const openEditor = (arc: LocalStoryArc | 'new') => { setEditor(arc); setDraft(arc === 'new' ? EMPTY : { title: arc.title, direction: arc.direction, stakes: arc.stakes, status: arc.status, progress: arc.progress, owner: arc.owner, mode: arc.mode }) }
  const save = () => { if (!draft.title.trim() || !editor) return; const arc: LocalStoryArc = { ...draft, title: draft.title.trim(), direction: draft.direction.trim(), stakes: draft.stakes.trim(), progress: Math.max(0, Math.min(100, draft.progress)), id: editor === 'new' ? `arc-${crypto.randomUUID()}` : editor.id }; persist({ ...campaign, storyArcs: editor === 'new' ? [...arcs, arc] : arcs.map((item) => item.id === arc.id ? arc : item) }); setEditor(null) }

  return <>
    <section className="campaign-section campaign-arcs"><header className="panel-heading"><div><span className="panel-kicker">Драматургическая карта</span><h2>Сюжетные линии</h2><p>Направление истории, ставки и текущее состояние — без жёсткого сценария.</p></div><Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Новая линия</Button></header><div className="campaign-arcs__summary"><span><strong>{arcs.filter((arc) => arc.status === 'active').length}</strong> в игре</span><span><strong>{arcs.filter((arc) => arc.progress >= 70 && arc.status !== 'resolved').length}</strong> близко к развязке</span><span><strong>{arcs.length}</strong> всего</span></div>{arcs.length ? <div className="campaign-arcs__board">{ARC_COLUMNS.map((column) => { const items = arcs.filter((arc) => arc.status === column.status); return <section key={column.status} data-status={column.status}><header><div><h3>{column.label}</h3><p>{column.hint}</p></div><span>{items.length}</span></header><div>{items.map((arc) => <article key={arc.id}><div className="campaign-arc__title"><Icon name="waypoints" size={17} /><h4>{arc.title}</h4><Button size="sm" icon="pencil" aria-label={`Редактировать линию: ${arc.title}`} onClick={() => openEditor(arc)} /></div><p>{arc.direction || 'Направление пока не задано.'}</p><div className="campaign-arc__stakes"><span>Ставки</span><strong>{arc.stakes || 'Не определены'}</strong></div><div className="campaign-arc__progress"><div><span>Прогресс</span><strong>{arc.progress}%</strong></div><i><span style={{ width: `${arc.progress}%` }} /></i></div></article>)}</div></section> })}</div> : <EmptyState icon="waypoints" title="Сюжетных линий пока нет" hint="Добавьте первое развивающееся противоречие: куда оно движется и что поставлено на карту." action={<Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Создать первую линию</Button>} />}</section>
    {editor && <Editor title={editor === 'new' ? 'Новая сюжетная линия' : 'Редактировать сюжетную линию'} close={() => setEditor(null)}><label htmlFor="arc-title">Название<input id="arc-title" autoFocus value={draft.title} placeholder="Договор с красной луной" onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label htmlFor="arc-direction">Куда движется линия<textarea id="arc-direction" rows={3} value={draft.direction} placeholder="Что произойдёт без вмешательства героев?" onChange={(event) => setDraft({ ...draft, direction: event.target.value })} /></label><label htmlFor="arc-stakes">Ставки<textarea id="arc-stakes" rows={3} value={draft.stakes} placeholder="Что можно потерять или приобрести?" onChange={(event) => setDraft({ ...draft, stakes: event.target.value })} /></label><div className="campaign-arc-form__row"><label htmlFor="arc-status">Состояние<select id="arc-status" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as LocalStoryArc['status'] })}><option value="planned">Замысел</option><option value="active">В игре</option><option value="resolved">Завершено</option></select></label><label htmlFor="arc-progress">Прогресс · {draft.progress}%<input id="arc-progress" type="range" min="0" max="100" step="10" value={draft.progress} onChange={(event) => setDraft({ ...draft, progress: Number(event.target.value) })} /></label></div><footer>{editor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, storyArcs: arcs.filter((item) => item.id !== editor.id) }); setEditor(null) }}>Удалить</Button>}<Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!draft.title.trim()} onClick={save}>Сохранить</Button></footer></Editor>}
  </>
}
