import { lazy, Suspense, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Badge, Button, EmptyState, Select } from '../../ds'
import { filterRelations, RELATION_TYPE, type RelationFilter } from '../../local/sessionFlow'
import type { LocalCampaignRelation, LocalRelationType } from '../../local/types'
import { Editor, type SectionProps } from './shared'

const RelationsGraph = lazy(() => import('./RelationsGraph'))

type Draft = Omit<LocalCampaignRelation, 'id'>
const blank = (fromId = '', toId = ''): Draft => ({ fromId, toId, label: '', type: 'other', direction: 'directed', visibility: 'master' })

export function RelationsSection({ campaign, persist }: SectionProps) {
  const navigate = useNavigate()
  const [editor, setEditor] = useState<LocalCampaignRelation | 'new' | null>(null)
  const [draft, setDraft] = useState<Draft>(blank())
  const [filter, setFilter] = useState<RelationFilter>({ visibility: 'all', type: 'all', entityId: '' })
  const [view, setView] = useState<'list' | 'graph'>('list')
  const activeEntities = campaign.entities.filter((entity) => entity.status !== 'archived')
  const entityName = (id: string) => campaign.entities.find((entity) => entity.id === id)?.name ?? 'Удалённая сущность'
  const openEditor = (relation: LocalCampaignRelation | 'new', preset?: Partial<Draft>) => { setEditor(relation); setDraft(relation === 'new' ? { ...blank(activeEntities[0]?.id, activeEntities[1]?.id), ...preset } : { fromId: relation.fromId, toId: relation.toId, label: relation.label, type: relation.type, direction: relation.direction, visibility: relation.visibility }) }
  const save = () => { if (!draft.label.trim() || draft.fromId === draft.toId || !editor) return; const relation: LocalCampaignRelation = { ...draft, label: draft.label.trim(), id: editor === 'new' ? `relation-${crypto.randomUUID()}` : editor.id }; persist({ ...campaign, relations: editor === 'new' ? [...campaign.relations, relation] : campaign.relations.map((item) => item.id === relation.id ? relation : item) }); setEditor(null) }
  const visible = filterRelations(campaign.relations, filter)

  return <>
    <section className="campaign-section campaign-relation-map"><div className="panel-heading"><div><span className="panel-kicker">Карта ведущего</span><h2>Связи мира</h2><p>Кто с кем связан, как именно и что об этом знают игроки.</p></div><div className="row"><div className="campaign-relation-map__filters" role="group" aria-label="Вид связей"><button className={view === 'list' ? 'active' : ''} aria-pressed={view === 'list'} onClick={() => setView('list')}>Список</button><button className={view === 'graph' ? 'active' : ''} aria-pressed={view === 'graph'} onClick={() => setView('graph')}>Граф</button></div><Button variant="primary" icon="plus" disabled={activeEntities.length < 2} onClick={() => openEditor('new')}>Новая связь</Button></div></div>
      {activeEntities.length < 2 ? <EmptyState icon="share-2" title="Нужно хотя бы две сущности" hint="Добавьте их в библиотеку, и здесь можно будет связать персонажей, места и фракции." action={<Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/library`)}>Открыть библиотеку</Button>} /> : <>
        <div className="campaign-relation-map__toolbar"><div className="campaign-relation-map__filters" aria-label="Видимость связей">{([['all', 'Все'], ['master', 'Только ведущим'], ['public', 'Для игроков']] as const).map(([value, label]) => <button key={value} className={filter.visibility === value ? 'active' : ''} onClick={() => setFilter({ ...filter, visibility: value })}>{label}</button>)}</div><Select aria-label="Тип связи" value={filter.type} onChange={(e) => setFilter({ ...filter, type: e.target.value as RelationFilter['type'] })}><option value="all">Все типы</option>{Object.entries(RELATION_TYPE).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select aria-label="Сущность" value={filter.entityId} onChange={(e) => setFilter({ ...filter, entityId: e.target.value })}><option value="">Все сущности</option>{activeEntities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</Select></div>
        {view === 'graph' ? <Suspense fallback={<p className="muted">Загружаем граф…</p>}><RelationsGraph campaign={campaign} relations={visible} onSelectRelation={(relation) => openEditor(relation)} onConnect={(fromId, toId) => openEditor('new', { fromId, toId })} onMoveNode={(entityId, position) => persist({ ...campaign, relationLayout: { ...campaign.relationLayout, [entityId]: position } })} /><p className="muted relation-graph__hint">Перетащите узел, чтобы расставить карту. Протяните линию между узлами, чтобы добавить связь. Пунктир — видно только ведущим.</p></Suspense>
          : visible.length ? <div className="campaign-relation-map__list">{visible.map((relation) => <article key={relation.id} aria-label={`Связь: ${entityName(relation.fromId)} — ${relation.label} — ${entityName(relation.toId)}`}><div className="campaign-relation-map__nodes"><strong>{entityName(relation.fromId)}</strong><span><i />{relation.direction === 'mutual' ? '⇄' : '→'} {relation.label}<i /></span><strong>{entityName(relation.toId)}</strong></div><footer><div className="row"><Badge size="sm" tone="accent">{RELATION_TYPE[relation.type]}</Badge><Badge tone={relation.visibility === 'master' ? 'warning' : 'success'} size="sm">{relation.visibility === 'master' ? 'Только ведущим' : 'Для игроков'}</Badge></div><Button size="sm" icon="pencil" onClick={() => openEditor(relation)}>Редактировать</Button></footer></article>)}</div>
          : <EmptyState icon="share-2" title={campaign.relations.length ? 'Под фильтр ничего не попало' : 'Связей пока нет'} hint={campaign.relations.length ? 'Сбросьте фильтры по типу или сущности.' : 'Соедините две сущности и подпишите, что между ними происходит.'} action={<Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Добавить связь</Button>} />}
      </>}</section>
    {editor && <Editor title={editor === 'new' ? 'Новая связь' : 'Редактировать связь'} close={() => setEditor(null)}>
      <div className="campaign-relation-form"><label htmlFor="relation-from">От<select id="relation-from" value={draft.fromId} onChange={(e) => setDraft({ ...draft, fromId: e.target.value })}>{activeEntities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label htmlFor="relation-to">К кому<select id="relation-to" value={draft.toId} onChange={(e) => setDraft({ ...draft, toId: e.target.value })}>{activeEntities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label></div>
      <label htmlFor="relation-label">Смысл связи<input id="relation-label" autoFocus value={draft.label} placeholder="доверяет, преследует, хранит тайну…" onChange={(e) => setDraft({ ...draft, label: e.target.value })} /></label>
      <div className="control-form__row"><label htmlFor="relation-type">Тип<select id="relation-type" value={draft.type} onChange={(e) => setDraft({ ...draft, type: e.target.value as LocalRelationType })}>{Object.entries(RELATION_TYPE).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label htmlFor="relation-direction">Направление<select id="relation-direction" value={draft.direction} onChange={(e) => setDraft({ ...draft, direction: e.target.value as Draft['direction'] })}><option value="directed">От первого ко второму</option><option value="mutual">Взаимная</option></select></label><label htmlFor="relation-visibility">Видимость<select id="relation-visibility" value={draft.visibility} onChange={(e) => setDraft({ ...draft, visibility: e.target.value as 'master' | 'public' })}><option value="master">Только ведущим</option><option value="public">Для игроков</option></select></label></div>
      {draft.fromId === draft.toId && <p className="local-session-error">Выберите две разные сущности.</p>}
      <footer>{editor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, relations: campaign.relations.filter((item) => item.id !== editor.id) }); setEditor(null) }}>Удалить</Button>}<Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!draft.label.trim() || draft.fromId === draft.toId} onClick={save}>Сохранить</Button></footer>
    </Editor>}
  </>
}
