import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Badge, Button, EmptyState } from '../../ds'
import type { LocalCampaignRelation } from '../../local/types'
import { Editor, type SectionProps } from './shared'

type Draft = Omit<LocalCampaignRelation, 'id'>

export function RelationsSection({ campaign, persist }: SectionProps) {
  const navigate = useNavigate()
  const [editor, setEditor] = useState<LocalCampaignRelation | 'new' | null>(null)
  const [draft, setDraft] = useState<Draft>({ fromId: '', toId: '', label: '', visibility: 'master' })
  const [visibility, setVisibility] = useState<'all' | 'master' | 'public'>('all')
  const entityName = (id: string) => campaign.entities.find((entity) => entity.id === id)?.name ?? 'Удалённая сущность'
  const openEditor = (relation: LocalCampaignRelation | 'new') => { const first = campaign.entities[0]?.id ?? ''; const second = campaign.entities[1]?.id ?? ''; setEditor(relation); setDraft(relation === 'new' ? { fromId: first, toId: second, label: '', visibility: 'master' } : { fromId: relation.fromId, toId: relation.toId, label: relation.label, visibility: relation.visibility }) }
  const save = () => { if (!draft.label.trim() || draft.fromId === draft.toId || !editor) return; const relation: LocalCampaignRelation = { ...draft, label: draft.label.trim(), id: editor === 'new' ? `relation-${crypto.randomUUID()}` : editor.id }; persist({ ...campaign, relations: editor === 'new' ? [...campaign.relations, relation] : campaign.relations.map((item) => item.id === relation.id ? relation : item) }); setEditor(null) }
  const visible = campaign.relations.filter((relation) => visibility === 'all' || relation.visibility === visibility)

  return <>
    <section className="campaign-section campaign-relation-map"><div className="panel-heading"><div><span className="panel-kicker">Карта ведущего</span><h2>Связи мира</h2><p>Кто с кем связан и что об этом знают игроки.</p></div><Button variant="primary" icon="plus" disabled={campaign.entities.length < 2} onClick={() => openEditor('new')}>Новая связь</Button></div>{campaign.entities.length < 2 ? <EmptyState icon="share-2" title="Нужно хотя бы две сущности" hint="Добавьте их в библиотеку, и здесь можно будет связать персонажей, места и фракции." action={<Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/library`)}>Открыть библиотеку</Button>} /> : <><div className="campaign-relation-map__filters" aria-label="Видимость связей">{([['all', 'Все'], ['master', 'Только ведущим'], ['public', 'Для игроков']] as const).map(([value, label]) => <button key={value} className={visibility === value ? 'active' : ''} onClick={() => setVisibility(value)}>{label}</button>)}</div>{visible.length ? <div className="campaign-relation-map__list">{visible.map((relation) => <article key={relation.id}><div className="campaign-relation-map__nodes"><strong>{entityName(relation.fromId)}</strong><span><i />{relation.label}<i /></span><strong>{entityName(relation.toId)}</strong></div><footer><Badge tone={relation.visibility === 'master' ? 'warning' : 'success'} size="sm">{relation.visibility === 'master' ? 'Только ведущим' : 'Для игроков'}</Badge><Button size="sm" icon="pencil" onClick={() => openEditor(relation)}>Редактировать</Button></footer></article>)}</div> : <EmptyState icon="share-2" title="Связей пока нет" hint="Соедините две сущности и подпишите, что между ними происходит." action={<Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Добавить связь</Button>} />}</>}</section>
    {editor && <Editor title={editor === 'new' ? 'Новая связь' : 'Редактировать связь'} close={() => setEditor(null)}><div className="campaign-relation-form"><label htmlFor="relation-from">От<select id="relation-from" value={draft.fromId} onChange={(event) => setDraft({ ...draft, fromId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label htmlFor="relation-to">К кому<select id="relation-to" value={draft.toId} onChange={(event) => setDraft({ ...draft, toId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label></div><label htmlFor="relation-label">Смысл связи<input id="relation-label" autoFocus value={draft.label} placeholder="доверяет, преследует, хранит тайну…" onChange={(event) => setDraft({ ...draft, label: event.target.value })} /></label><label htmlFor="relation-visibility">Видимость<select id="relation-visibility" value={draft.visibility} onChange={(event) => setDraft({ ...draft, visibility: event.target.value as 'master' | 'public' })}><option value="master">Только ведущим</option><option value="public">Для игроков</option></select></label>{draft.fromId === draft.toId && <p className="local-session-error">Выберите две разные сущности.</p>}<footer>{editor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, relations: campaign.relations.filter((item) => item.id !== editor.id) }); setEditor(null) }}>Удалить</Button>}<Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!draft.label.trim() || draft.fromId === draft.toId} onClick={save}>Сохранить</Button></footer></Editor>}
  </>
}
