import { useEffect, useState, type ReactNode } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Badge, Button, EmptyState, Icon, Select } from '../ds'
import { localCampaignCatalog, type LocalCampaignEntity, type LocalCampaignEntityType, type LocalCampaignRecord, type LocalCampaignRelation } from '../fixtures/localCampaignCatalog'

const ENTITY_TYPES: Array<{ value: LocalCampaignEntityType; label: string }> = [
  ['character', 'Персонаж'], ['npc', 'Персонаж ведущего'], ['creature', 'Существо'], ['location', 'Локация'], ['faction', 'Фракция'], ['rumor', 'Слух'], ['item', 'Предмет'], ['audience', 'Аудитория'], ['note', 'Заметка'], ['letter', 'Письмо'], ['handout', 'Раздаточный материал'], ['map', 'Карта'], ['home-rule', 'Домашнее правило'],
].map(([value, label]) => ({ value: value as LocalCampaignEntityType, label }))
const ENTITY_LABEL = Object.fromEntries(ENTITY_TYPES.map((item) => [item.value, item.label])) as Record<LocalCampaignEntityType, string>

export function LocalNewCampaignPage() {
  const { campaignId = '', section = 'overview' } = useParams()
  const navigate = useNavigate()
  const initial = localCampaignCatalog.find(campaignId)
  const [campaign, setCampaign] = useState(initial)
  const [note, setNote] = useState('')
  const [sessionTitle, setSessionTitle] = useState(initial?.firstSessionTitle ?? '')
  const [sessionObjective, setSessionObjective] = useState(initial?.firstSessionObjective ?? '')
  const [editingNote, setEditingNote] = useState<number | null>(null)
  const [entityEditor, setEntityEditor] = useState<LocalCampaignEntity | 'new' | null>(null)
  const [entityDraft, setEntityDraft] = useState<Omit<LocalCampaignEntity, 'id'>>({ type: 'npc', name: '', description: '', tags: [] })
  const [entityQuery, setEntityQuery] = useState('')
  const [relationEditor, setRelationEditor] = useState<LocalCampaignRelation | 'new' | null>(null)
  const [relationDraft, setRelationDraft] = useState<Omit<LocalCampaignRelation, 'id'>>({ fromId: '', toId: '', label: '', visibility: 'master' })
  const [relationVisibility, setRelationVisibility] = useState<'all' | 'master' | 'public'>('all')
  const [editor, setEditor] = useState<'campaign' | 'session' | null>(null)
  const [details, setDetails] = useState({ name: initial?.name ?? '', idea: initial?.idea ?? '', activeTime: initial?.activeTime ?? '' })
  useEffect(() => { if (!editor) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setEditor(null) }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [editor])
  if (!campaign) return <Navigate to="/" replace />
  const persist = (next: LocalCampaignRecord) => setCampaign(localCampaignCatalog.update(next))
  const addNote = () => { const text = note.trim(); if (!text) return; persist({ ...campaign, notes: [...campaign.notes, text] }); setNote('') }
  const saveSession = () => { if (!sessionTitle.trim()) return; persist({ ...campaign, firstSessionTitle: sessionTitle.trim(), firstSessionObjective: sessionObjective.trim(), sessions: 1 }); setEditor(null) }
  const saveCampaign = () => { if (!details.name.trim()) return; persist({ ...campaign, name: details.name.trim(), idea: details.idea.trim(), activeTime: details.activeTime.trim() || 'Время ещё не задано' }); setEditor(null) }
  const ready = campaign.notes.length > 0 && Boolean(campaign.firstSessionTitle)

  const openSessionEditor = () => { setSessionTitle(campaign.firstSessionTitle); setSessionObjective(campaign.firstSessionObjective); setEditor('session') }
  const saveNote = () => { if (editingNote === null || !note.trim()) return; const notes = [...campaign.notes]; notes[editingNote] = note.trim(); persist({ ...campaign, notes }); setNote(''); setEditingNote(null) }
  const removeNote = (index: number) => persist({ ...campaign, notes: campaign.notes.filter((_, noteIndex) => noteIndex !== index) })
  const openEntityEditor = (entity: LocalCampaignEntity | 'new') => { setEntityEditor(entity); setEntityDraft(entity === 'new' ? { type: 'npc', name: '', description: '', tags: [] } : { type: entity.type, name: entity.name, description: entity.description, tags: entity.tags }) }
  const saveEntity = () => {
    if (!entityDraft.name.trim()) return
    const entity: LocalCampaignEntity = { ...entityDraft, name: entityDraft.name.trim(), description: entityDraft.description.trim(), tags: entityDraft.tags.map((tag) => tag.trim().toLocaleLowerCase()).filter(Boolean), id: entityEditor === 'new' ? `entity-${crypto.randomUUID()}` : entityEditor!.id }
    persist({ ...campaign, entities: entityEditor === 'new' ? [...campaign.entities, entity] : campaign.entities.map((item) => item.id === entity.id ? entity : item) })
    setEntityEditor(null)
  }
  const visibleEntities = campaign.entities.filter((entity) => !entityQuery.trim() || `${entity.name} ${entity.tags.join(' ')}`.toLocaleLowerCase().includes(entityQuery.trim().toLocaleLowerCase()))
  const entityName = (id: string) => campaign.entities.find((entity) => entity.id === id)?.name ?? 'Удалённая сущность'
  const openRelationEditor = (relation: LocalCampaignRelation | 'new') => { const first = campaign.entities[0]?.id ?? ''; const second = campaign.entities[1]?.id ?? ''; setRelationEditor(relation); setRelationDraft(relation === 'new' ? { fromId: first, toId: second, label: '', visibility: 'master' } : { fromId: relation.fromId, toId: relation.toId, label: relation.label, visibility: relation.visibility }) }
  const saveRelation = () => { if (!relationDraft.label.trim() || relationDraft.fromId === relationDraft.toId) return; const relation: LocalCampaignRelation = { ...relationDraft, label: relationDraft.label.trim(), id: relationEditor === 'new' ? `relation-${crypto.randomUUID()}` : relationEditor!.id }; persist({ ...campaign, relations: relationEditor === 'new' ? [...campaign.relations, relation] : campaign.relations.map((item) => item.id === relation.id ? relation : item) }); setRelationEditor(null) }
  const visibleRelations = campaign.relations.filter((relation) => relationVisibility === 'all' || relation.visibility === relationVisibility)

  if (ready) return <main className="created-dashboard">
    <header className="new-campaign-room__topbar"><Link to="/"><Icon name="arrow-left" size={16} /> Все кампании</Link><div><Badge tone="success" dot>Основа готова</Badge><Badge tone="neutral">Сохранено в браузере</Badge></div></header>
    <section className="created-dashboard__hero"><div><span className="panel-kicker">Рабочее пространство кампании</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><Button icon="pencil" onClick={() => { setDetails({ name: campaign.name, idea: campaign.idea, activeTime: campaign.activeTime }); setEditor('campaign') }}>Настройки кампании</Button></section>
    <nav className="campaign-section-nav" aria-label="Разделы кампании"><Link className={section === 'overview' ? 'active' : ''} to={`/local/campaign/${campaign.id}/overview`}><Icon name="layout-dashboard" size={17} />Обзор</Link><Link className={section === 'library' ? 'active' : ''} to={`/local/campaign/${campaign.id}/library`}><Icon name="library" size={17} />Библиотека <span>{campaign.entities.length}</span></Link><Link className={section === 'map' ? 'active' : ''} to={`/local/campaign/${campaign.id}/map`}><Icon name="share-2" size={17} />Связи <span>{campaign.relations.length}</span></Link><Link className={section === 'world' ? 'active' : ''} to={`/local/campaign/${campaign.id}/world`}><Icon name="book-open" size={17} />Заметки <span>{campaign.notes.length}</span></Link><Link className={section === 'session' ? 'active' : ''} to={`/local/campaign/${campaign.id}/session`}><Icon name="calendar" size={17} />Сессия</Link></nav>
    {section === 'overview' && <><div className="campaign-next-action"><div><span className="panel-kicker">Следующее действие</span><h2>Подготовить «{campaign.firstSessionTitle}»</h2><p>{campaign.firstSessionObjective || 'Добавьте цель сессии, чтобы зафиксировать ожидаемый результат игры.'}</p></div><Button variant="primary" icon="arrow-right" onClick={() => navigate(`/local/campaign/${campaign.id}/session`)}>Открыть подготовку</Button></div><div className="created-dashboard__grid"><section><div className="panel-heading"><div><span className="panel-kicker">Мир кампании</span><h2>Последние опорные точки</h2></div><Button onClick={() => navigate(`/local/campaign/${campaign.id}/world`)}>Открыть мир</Button></div><ol>{campaign.notes.slice(0, 4).map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></li>)}</ol></section><aside><span className="panel-kicker">Состояние кампании</span><dl><div><dt>Текущее время</dt><dd>{campaign.activeTime}</dd></div><div><dt>Ведущий</dt><dd>{campaign.masters}</dd></div><div><dt>Сессий</dt><dd>{campaign.sessions}</dd></div></dl><p><Icon name="hard-drive" size={15} /> Изменения сохраняются локально.</p></aside></div></>}
    {section === 'world' && <section className="campaign-section"><div className="panel-heading"><div><span className="panel-kicker">Контекст для подготовки</span><h2>Мир кампании</h2><p>Факты, места и персонажи, на которые можно опираться во время игры.</p></div><span className="panel-state">{campaign.notes.length}</span></div><ol className="campaign-world-list">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p><div><Button icon="pencil" aria-label={`Редактировать: ${item}`} onClick={() => { setEditingNote(index); setNote(item) }} /><Button icon="trash-2" aria-label={`Удалить: ${item}`} onClick={() => removeNote(index)} /></div></li>)}</ol><Capture value={note} setValue={setNote} add={editingNote === null ? addNote : saveNote} label={editingNote === null ? 'Добавить' : 'Сохранить'} />{editingNote !== null && <Button onClick={() => { setEditingNote(null); setNote('') }}>Отменить редактирование</Button>}</section>}
    {section === 'library' && <section className="campaign-section campaign-local-library"><div className="panel-heading"><div><span className="panel-kicker">Единый справочник</span><h2>Библиотека кампании</h2><p>Персонажи, места, фракции и материалы этой истории.</p></div><Button variant="primary" icon="plus" onClick={() => openEntityEditor('new')}>Новая сущность</Button></div><div className="campaign-local-library__search"><Icon name="search" size={17} /><input value={entityQuery} aria-label="Поиск по библиотеке" placeholder="Найти по названию или тегу…" onChange={(event) => setEntityQuery(event.target.value)} /></div>{visibleEntities.length ? <div className="campaign-local-library__grid">{visibleEntities.map((entity) => <article key={entity.id}><span className="panel-kicker">{ENTITY_LABEL[entity.type]}</span><h3>{entity.name}</h3><p>{entity.description || 'Описание пока не добавлено.'}</p><footer><div>{entity.tags.map((tag) => <Badge size="sm" key={tag}>#{tag}</Badge>)}</div><Button size="sm" icon="pencil" onClick={() => openEntityEditor(entity)}>Редактировать</Button></footer></article>)}</div> : <EmptyState icon="library" title={campaign.entities.length ? 'Ничего не найдено' : 'Библиотека пока пуста'} hint={campaign.entities.length ? 'Измените поисковый запрос.' : 'Создайте первого персонажа, место или важный предмет.'} action={!campaign.entities.length ? <Button variant="primary" icon="plus" onClick={() => openEntityEditor('new')}>Создать сущность</Button> : undefined} />}</section>}
    {section === 'map' && <section className="campaign-section campaign-relation-map"><div className="panel-heading"><div><span className="panel-kicker">Карта ведущего</span><h2>Связи мира</h2><p>Кто с кем связан и что об этом знают игроки.</p></div><Button variant="primary" icon="plus" disabled={campaign.entities.length < 2} onClick={() => openRelationEditor('new')}>Новая связь</Button></div>{campaign.entities.length < 2 ? <EmptyState icon="share-2" title="Нужно хотя бы две сущности" hint="Добавьте их в библиотеку, и здесь можно будет связать персонажей, места и фракции." action={<Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/library`)}>Открыть библиотеку</Button>} /> : <><div className="campaign-relation-map__filters" aria-label="Видимость связей">{([['all', 'Все'], ['master', 'Только ведущим'], ['public', 'Для игроков']] as const).map(([value, label]) => <button key={value} className={relationVisibility === value ? 'active' : ''} onClick={() => setRelationVisibility(value)}>{label}</button>)}</div>{visibleRelations.length ? <div className="campaign-relation-map__list">{visibleRelations.map((relation) => <article key={relation.id}><div className="campaign-relation-map__nodes"><strong>{entityName(relation.fromId)}</strong><span><i />{relation.label}<i /></span><strong>{entityName(relation.toId)}</strong></div><footer><Badge tone={relation.visibility === 'master' ? 'warning' : 'success'} size="sm">{relation.visibility === 'master' ? 'Только ведущим' : 'Для игроков'}</Badge><Button size="sm" icon="pencil" onClick={() => openRelationEditor(relation)}>Редактировать</Button></footer></article>)}</div> : <EmptyState icon="share-2" title="Связей пока нет" hint="Соедините две сущности и подпишите, что между ними происходит." action={<Button variant="primary" icon="plus" onClick={() => openRelationEditor('new')}>Добавить связь</Button>} />}</>}</section>}
    {section === 'session' && <section className="campaign-section campaign-session-sheet"><div><div className="panel-heading"><div><span className="panel-kicker">Сессия 01 · черновик</span><h2>{campaign.firstSessionTitle}</h2></div><Badge tone="warning">Подготовка</Badge></div><div className="campaign-session-objective"><span>Цель сессии</span><p>{campaign.firstSessionObjective || 'Цель пока не сформулирована.'}</p></div></div><aside><span className="panel-kicker">Управление</span><p>Здесь меняются данные сессии. Запуск игры появится на следующем этапе рабочего потока.</p><Button variant="primary" block icon="pencil" onClick={openSessionEditor}>Редактировать сессию</Button></aside></section>}
    {editor === 'campaign' && <Editor title="Редактировать кампанию" close={() => setEditor(null)}><label htmlFor="local-edit-name">Название<input id="local-edit-name" autoFocus value={details.name} onChange={(e) => setDetails({ ...details, name: e.target.value })} /></label><label htmlFor="local-edit-idea">Короткая идея<textarea id="local-edit-idea" rows={4} value={details.idea} onChange={(e) => setDetails({ ...details, idea: e.target.value })} /></label><label htmlFor="local-edit-time">Текущее время<input id="local-edit-time" value={details.activeTime} onChange={(e) => setDetails({ ...details, activeTime: e.target.value })} /></label><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!details.name.trim()} onClick={saveCampaign}>Сохранить</Button></footer></Editor>}
    {editor === 'session' && <Editor title="Редактировать сессию" close={() => setEditor(null)}><label htmlFor="local-session-name">Название<input id="local-session-name" autoFocus value={sessionTitle} onChange={(e) => setSessionTitle(e.target.value)} /></label><label htmlFor="local-session-objective">Цель сессии<textarea id="local-session-objective" rows={4} value={sessionObjective} placeholder="Что должно измениться к концу игры?" onChange={(e) => setSessionObjective(e.target.value)} /></label><p className="muted">Сессия остаётся черновиком до явного начала игры.</p><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!sessionTitle.trim()} onClick={saveSession}>Сохранить</Button></footer></Editor>}
    {entityEditor && <Editor title={entityEditor === 'new' ? 'Новая сущность' : 'Редактировать сущность'} close={() => setEntityEditor(null)}><label htmlFor="local-entity-type">Тип<Select id="local-entity-type" value={entityDraft.type} onChange={(event) => setEntityDraft({ ...entityDraft, type: event.target.value as LocalCampaignEntityType })}>{ENTITY_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</Select></label><label htmlFor="local-entity-name">Название<input id="local-entity-name" autoFocus value={entityDraft.name} onChange={(event) => setEntityDraft({ ...entityDraft, name: event.target.value })} /></label><label htmlFor="local-entity-description">Рабочее описание<textarea id="local-entity-description" rows={4} value={entityDraft.description} onChange={(event) => setEntityDraft({ ...entityDraft, description: event.target.value })} /></label><label htmlFor="local-entity-tags">Теги<input id="local-entity-tags" value={entityDraft.tags.join(', ')} placeholder="важное, первая сессия" onChange={(event) => setEntityDraft({ ...entityDraft, tags: event.target.value.split(',') })} /></label><footer>{entityEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, entities: campaign.entities.filter((item) => item.id !== entityEditor.id), relations: campaign.relations.filter((relation) => relation.fromId !== entityEditor.id && relation.toId !== entityEditor.id) }); setEntityEditor(null) }}>Удалить</Button>}<Button onClick={() => setEntityEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!entityDraft.name.trim()} onClick={saveEntity}>Сохранить</Button></footer></Editor>}
    {relationEditor && <Editor title={relationEditor === 'new' ? 'Новая связь' : 'Редактировать связь'} close={() => setRelationEditor(null)}><div className="campaign-relation-form"><label htmlFor="relation-from">От<select id="relation-from" value={relationDraft.fromId} onChange={(event) => setRelationDraft({ ...relationDraft, fromId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label htmlFor="relation-to">К кому<select id="relation-to" value={relationDraft.toId} onChange={(event) => setRelationDraft({ ...relationDraft, toId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label></div><label htmlFor="relation-label">Смысл связи<input id="relation-label" autoFocus value={relationDraft.label} placeholder="доверяет, преследует, хранит тайну…" onChange={(event) => setRelationDraft({ ...relationDraft, label: event.target.value })} /></label><label htmlFor="relation-visibility">Видимость<select id="relation-visibility" value={relationDraft.visibility} onChange={(event) => setRelationDraft({ ...relationDraft, visibility: event.target.value as 'master' | 'public' })}><option value="master">Только ведущим</option><option value="public">Для игроков</option></select></label>{relationDraft.fromId === relationDraft.toId && <p className="local-session-error">Выберите две разные сущности.</p>}<footer>{relationEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, relations: campaign.relations.filter((item) => item.id !== relationEditor.id) }); setRelationEditor(null) }}>Удалить</Button>}<Button onClick={() => setRelationEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!relationDraft.label.trim() || relationDraft.fromId === relationDraft.toId} onClick={saveRelation}>Сохранить</Button></footer></Editor>}
  </main>

  return <main className="new-campaign-room"><header className="new-campaign-room__topbar"><Link to="/"><Icon name="arrow-left" size={16} /> Все кампании</Link><Badge tone="neutral" dot>Сохранено в браузере</Badge></header><section className="new-campaign-room__hero"><div><span className="panel-kicker">Новая локальная кампания</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><div className="new-campaign-room__readiness"><span>Первичная настройка</span><strong>{Number(Boolean(campaign.firstSessionTitle)) + Number(campaign.notes.length > 0)} / 2</strong></div></section><div className="new-campaign-room__layout"><section className="new-campaign-room__main">{!campaign.notes.length ? <EmptyState icon="book-open" title="Мир пока пуст" hint="Запишите первый факт, персонажа или место." action={<Capture value={note} setValue={setNote} add={addNote} />} /> : <><div className="panel-heading"><div><span className="panel-kicker">Первые опорные точки</span><h2>Заметки кампании</h2></div></div><ol className="new-campaign-room__notes">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></li>)}</ol><Capture value={note} setValue={setNote} add={addNote} /></>}</section><aside className="new-campaign-room__setup"><span className="panel-kicker">Быстрый старт</span><h2>Подготовьте первую игру</h2><label htmlFor="first-session">Название первой сессии<input id="first-session" value={sessionTitle} placeholder="Встреча у старых ворот" onChange={(e) => setSessionTitle(e.target.value)} /></label><Button variant="primary" block disabled={!sessionTitle.trim()} onClick={saveSession}>Создать сессию и открыть дашборд</Button><div className="new-campaign-room__steps"><span className={campaign.notes.length ? 'done' : ''}><Icon name={campaign.notes.length ? 'check' : 'circle'} size={16} /> Добавить опорную точку</span><span><Icon name="circle" size={16} /> Создать первую сессию</span></div></aside></div><p className="local-session-footnote"><Icon name="hard-drive" size={14} /> После выполнения двух шагов автоматически откроется дашборд кампании.</p></main>
}

function Capture({ value, setValue, add, label = 'Добавить' }: { value: string; setValue: (value: string) => void; add: () => void; label?: string }) { return <div className="new-campaign-room__capture"><input value={value} aria-label="Новая опорная точка" placeholder="Добавить опорную точку…" onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') add() }} /><Button icon={label === 'Добавить' ? 'plus' : 'check'} disabled={!value.trim()} onClick={add}>{label}</Button></div> }
function Editor({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(e) => { if (e.currentTarget === e.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><span className="panel-kicker">Локальные параметры</span><h2>{title}</h2>{children}</section></div> }
