import { useEffect, useState, type ReactNode } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Badge, Button, Card, EmptyState, Icon, Select } from '../ds'
import { localCampaignCatalog, type LocalCampaignEntity, type LocalCampaignEntityType, type LocalCampaignRecord, type LocalCampaignRelation, type LocalSessionScene, type LocalStoryArc } from '../fixtures/localCampaignCatalog'
import { LocalThemeControl } from '../components/LocalThemeControl'
import { LocalCampaignControlCenter } from '../components/LocalCampaignControlCenter'
import { LocalSessionContext } from '../components/LocalSessionContext'
import { LocalSessionReview } from '../components/LocalSessionReview'
import { LocalLiveSession } from '../components/LocalLiveSession'

const ENTITY_TYPES: Array<{ value: LocalCampaignEntityType; label: string }> = [
  ['character', 'Персонаж'], ['npc', 'Персонаж ведущего'], ['creature', 'Существо'], ['location', 'Локация'], ['faction', 'Фракция'], ['rumor', 'Слух'], ['item', 'Предмет'], ['audience', 'Аудитория'], ['note', 'Заметка'], ['letter', 'Письмо'], ['handout', 'Раздаточный материал'], ['map', 'Карта'], ['home-rule', 'Домашнее правило'],
].map(([value, label]) => ({ value: value as LocalCampaignEntityType, label }))
const ENTITY_LABEL = Object.fromEntries(ENTITY_TYPES.map((item) => [item.value, item.label])) as Record<LocalCampaignEntityType, string>

export function LocalNewCampaignPage() {
  const { campaignId = '', section = 'overview' } = useParams()
  const navigate = useNavigate()
  const initial = localCampaignCatalog.find(campaignId)
  const [campaign, setCampaign] = useState(initial)
  const [note, setNote] = useState('')
  const [sessionTitle, setSessionTitle] = useState(initial?.firstSessionTitle ?? '')
  const [sessionObjective, setSessionObjective] = useState(initial?.firstSessionObjective ?? '')
  const [sessionOpening, setSessionOpening] = useState(initial?.firstSessionOpening ?? '')
  const [sessionMeta, setSessionMeta] = useState({ master: initial?.firstSessionMaster ?? '', arcId: initial?.firstSessionArcId ?? '', inGameTime: initial?.firstSessionInGameTime ?? '', idea: initial?.firstSessionIdea ?? '' })
  const [sceneEditor, setSceneEditor] = useState<LocalSessionScene | 'new' | null>(null)
  const [sceneDraft, setSceneDraft] = useState<Omit<LocalSessionScene, 'id'>>({ title: '', purpose: '', kind: 'scene', priority: 'desired', status: 'prepared' })
  const [editingNote, setEditingNote] = useState<number | null>(null)
  const [entityEditor, setEntityEditor] = useState<LocalCampaignEntity | 'new' | null>(null)
  const [entityDraft, setEntityDraft] = useState<Omit<LocalCampaignEntity, 'id'>>({ type: 'npc', name: '', description: '', tags: [], visibility: 'master', status: 'active' })
  const [entityQuery, setEntityQuery] = useState('')
  const [relationEditor, setRelationEditor] = useState<LocalCampaignRelation | 'new' | null>(null)
  const [relationDraft, setRelationDraft] = useState<Omit<LocalCampaignRelation, 'id'>>({ fromId: '', toId: '', label: '', visibility: 'master' })
  const [relationVisibility, setRelationVisibility] = useState<'all' | 'master' | 'public'>('all')
  const [arcEditor, setArcEditor] = useState<LocalStoryArc | 'new' | null>(null)
  const [arcDraft, setArcDraft] = useState<Omit<LocalStoryArc, 'id'>>({ title: '', direction: '', stakes: '', status: 'planned', progress: 0, owner: '', mode: 'foreground' })
  const [editor, setEditor] = useState<'campaign' | 'session' | null>(null)
  const [details, setDetails] = useState({ name: initial?.name ?? '', idea: initial?.idea ?? '', activeTime: initial?.activeTime ?? '', masters: initial?.masters ?? '' })
  useEffect(() => { if (!editor) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setEditor(null) }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [editor])
  if (!campaign) return <Navigate to="/" replace />
  const persist = (next: LocalCampaignRecord) => setCampaign(localCampaignCatalog.update(next))
  const addNote = () => { const text = note.trim(); if (!text) return; persist({ ...campaign, notes: [...campaign.notes, text] }); setNote('') }
  const saveSession = () => { if (!sessionTitle.trim()) return; persist({ ...campaign, firstSessionTitle: sessionTitle.trim(), firstSessionObjective: sessionObjective.trim(), firstSessionOpening: sessionOpening.trim(), firstSessionMaster: sessionMeta.master.trim(), firstSessionArcId: sessionMeta.arcId, firstSessionInGameTime: sessionMeta.inGameTime.trim(), firstSessionIdea: sessionMeta.idea.trim(), firstSessionStatus: 'draft', sessions: 1 }); setEditor(null) }
  const saveCampaign = () => { if (!details.name.trim()) return; persist({ ...campaign, name: details.name.trim(), idea: details.idea.trim(), activeTime: details.activeTime.trim() || 'Время ещё не задано', masters: details.masters.trim() }); setEditor(null) }
  const ready = campaign.notes.length > 0 && Boolean(campaign.firstSessionTitle)

  const openSessionEditor = () => { setSessionTitle(campaign.firstSessionTitle); setSessionObjective(campaign.firstSessionObjective); setSessionOpening(campaign.firstSessionOpening); setSessionMeta({ master: campaign.firstSessionMaster, arcId: campaign.firstSessionArcId, inGameTime: campaign.firstSessionInGameTime, idea: campaign.firstSessionIdea }); setEditor('session') }
  const openSceneEditor = (scene: LocalSessionScene | 'new') => { setSceneEditor(scene); setSceneDraft(scene === 'new' ? { title: '', purpose: '', kind: 'scene', priority: 'desired', status: 'prepared' } : { title: scene.title, purpose: scene.purpose, kind: scene.kind, priority: scene.priority, status: scene.status }) }
  const saveScene = () => { if (!sceneDraft.title.trim()) return; const scene: LocalSessionScene = { ...sceneDraft, id: sceneEditor === 'new' ? `scene-${crypto.randomUUID()}` : sceneEditor!.id, title: sceneDraft.title.trim(), purpose: sceneDraft.purpose.trim() }; persist({ ...campaign, firstSessionScenes: sceneEditor === 'new' ? [...campaign.firstSessionScenes, scene] : campaign.firstSessionScenes.map((item) => item.id === scene.id ? scene : item), firstSessionStatus: 'draft' }); setSceneEditor(null) }
  const sessionPrepared = Boolean(campaign.firstSessionObjective && campaign.firstSessionOpening && campaign.firstSessionScenes.length)
  const startSession = () => { persist({ ...campaign, firstSessionStatus: 'active', firstSessionCurrentSceneId: campaign.firstSessionCurrentSceneId || campaign.firstSessionScenes[0]?.id || '' }); navigate(`/local/campaign/${campaign.id}/play`) }
  const currentScene = campaign.firstSessionScenes.find((scene) => scene.id === campaign.firstSessionCurrentSceneId) ?? campaign.firstSessionScenes[0]
  const saveNote = () => { if (editingNote === null || !note.trim()) return; const notes = [...campaign.notes]; notes[editingNote] = note.trim(); persist({ ...campaign, notes }); setNote(''); setEditingNote(null) }
  const removeNote = (index: number) => persist({ ...campaign, notes: campaign.notes.filter((_, noteIndex) => noteIndex !== index) })
  const openEntityEditor = (entity: LocalCampaignEntity | 'new') => { setEntityEditor(entity); setEntityDraft(entity === 'new' ? { type: 'npc', name: '', description: '', tags: [], visibility: 'master', status: 'active' } : { type: entity.type, name: entity.name, description: entity.description, tags: entity.tags, visibility: entity.visibility, status: entity.status }) }
  const saveEntity = () => {
    if (!entityDraft.name.trim()) return
    const entity: LocalCampaignEntity = { ...entityDraft, name: entityDraft.name.trim(), description: entityDraft.description.trim(), tags: entityDraft.tags.map((tag) => tag.trim().toLocaleLowerCase()).filter(Boolean), id: entityEditor === 'new' ? `entity-${crypto.randomUUID()}` : entityEditor!.id }
    persist({ ...campaign, entities: entityEditor === 'new' ? [...campaign.entities, entity] : campaign.entities.map((item) => item.id === entity.id ? entity : item) })
    setEntityEditor(null)
  }
  const visibleEntities = campaign.entities.filter((entity) => !entityQuery.trim() || `${entity.name} ${entity.tags.join(' ')}`.toLocaleLowerCase().includes(entityQuery.trim().toLocaleLowerCase()))
  const entityName = (id: string) => campaign.entities.find((entity) => entity.id === id)?.name ?? 'Удалённая сущность'
  const openRelationEditor = (relation: LocalCampaignRelation | 'new') => { const first = campaign.entities[0]?.id ?? ''; const second = campaign.entities[1]?.id ?? ''; setRelationEditor(relation); setRelationDraft(relation === 'new' ? { fromId: first, toId: second, label: '', visibility: 'master' } : { fromId: relation.fromId, toId: relation.toId, label: relation.label, visibility: relation.visibility }) }
  const saveRelation = () => { if (!relationDraft.label.trim() || relationDraft.fromId === relationDraft.toId) return; const relation: LocalCampaignRelation = { ...relationDraft, label: relationDraft.label.trim(), id: relationEditor === 'new' ? `relation-${crypto.randomUUID()}` : relationEditor!.id }; persist({ ...campaign, relations: relationEditor === 'new' ? [...campaign.relations, relation] : campaign.relations.map((item) => item.id === relation.id ? relation : item) }); setRelationEditor(null) }
  const visibleRelations = campaign.relations.filter((relation) => relationVisibility === 'all' || relation.visibility === relationVisibility)
  const openArcEditor = (arc: LocalStoryArc | 'new') => { setArcEditor(arc); setArcDraft(arc === 'new' ? { title: '', direction: '', stakes: '', status: 'planned', progress: 0, owner: '', mode: 'foreground' } : { title: arc.title, direction: arc.direction, stakes: arc.stakes, status: arc.status, progress: arc.progress, owner: arc.owner, mode: arc.mode }) }
  const saveArc = () => { if (!arcDraft.title.trim()) return; const arc: LocalStoryArc = { ...arcDraft, title: arcDraft.title.trim(), direction: arcDraft.direction.trim(), stakes: arcDraft.stakes.trim(), progress: Math.max(0, Math.min(100, arcDraft.progress)), id: arcEditor === 'new' ? `arc-${crypto.randomUUID()}` : arcEditor!.id }; persist({ ...campaign, storyArcs: arcEditor === 'new' ? [...campaign.storyArcs, arc] : campaign.storyArcs.map((item) => item.id === arc.id ? arc : item) }); setArcEditor(null) }

  if (ready && section === 'play') return <LocalLiveSession campaign={campaign} persist={persist} startSession={startSession} currentScene={currentScene} />
  if (ready) return <main className="target-dashboard created-dashboard">
    <header className="local-dashboard-header"><div className="local-dashboard-header__utility"><Link to="/"><Icon name="arrow-left" size={16} /> Кампании</Link><strong>{campaign.name}</strong><div className="row"><Badge tone="neutral" dot>Локальные данные</Badge><LocalThemeControl /></div></div><nav className="local-dashboard-nav" aria-label="Разделы кампании"><Link className={section === 'overview' ? 'active' : ''} to={`/local/campaign/${campaign.id}/overview`}><Icon name="layout-dashboard" size={16} /> Обзор</Link><Link className={section === 'session' ? 'active' : ''} to={`/local/campaign/${campaign.id}/session`}><Icon name="clapperboard" size={16} /> Сессия</Link><Link className={section === 'arcs' ? 'active' : ''} to={`/local/campaign/${campaign.id}/arcs`}><Icon name="waypoints" size={16} /> Сюжет</Link><Link className={section === 'control' ? 'active' : ''} to={`/local/campaign/${campaign.id}/control`}><Icon name="list-checks" size={16} /> Пульт</Link><Link className={section === 'library' ? 'active' : ''} to={`/local/campaign/${campaign.id}/library`}><Icon name="library" size={16} /> Библиотека</Link><Link className={section === 'map' ? 'active' : ''} to={`/local/campaign/${campaign.id}/map`}><Icon name="share-2" size={16} /> Связи</Link><Link className={section === 'world' ? 'active' : ''} to={`/local/campaign/${campaign.id}/world`}><Icon name="book-open" size={16} /> Заметки</Link></nav></header>
    {section === 'overview' && <section className="target-dashboard__hero"><div><span className="panel-kicker">Панель кампании</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><div className="target-dashboard__hero-actions"><Button icon="pencil" onClick={() => { setDetails({ name: campaign.name, idea: campaign.idea, activeTime: campaign.activeTime, masters: campaign.masters }); setEditor('campaign') }}>Редактировать</Button><div className="target-dashboard__time"><span>Текущее время</span><strong>{campaign.activeTime}</strong></div></div></section>}
    {section === 'overview' && <CampaignOverview campaign={campaign} persist={persist} navigate={navigate} />}
    {section === 'arcs' && <StoryArcsBoard arcs={campaign.storyArcs} openEditor={openArcEditor} />}
    {section === 'control' && <LocalCampaignControlCenter campaign={campaign} persist={persist} />}
    {section === 'world' && <section className="campaign-section"><div className="panel-heading"><div><span className="panel-kicker">Контекст для подготовки</span><h2>Мир кампании</h2><p>Факты, места и персонажи, на которые можно опираться во время игры.</p></div><span className="panel-state">{campaign.notes.length}</span></div><ol className="campaign-world-list">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p><div><Button icon="pencil" aria-label={`Редактировать: ${item}`} onClick={() => { setEditingNote(index); setNote(item) }} /><Button icon="trash-2" aria-label={`Удалить: ${item}`} onClick={() => removeNote(index)} /></div></li>)}</ol><Capture value={note} setValue={setNote} add={editingNote === null ? addNote : saveNote} label={editingNote === null ? 'Добавить' : 'Сохранить'} />{editingNote !== null && <Button onClick={() => { setEditingNote(null); setNote('') }}>Отменить редактирование</Button>}</section>}
    {section === 'library' && <section className="campaign-section campaign-local-library"><div className="panel-heading"><div><span className="panel-kicker">Единый справочник</span><h2>Библиотека кампании</h2><p>Персонажи, места, фракции и материалы этой истории.</p></div><Button variant="primary" icon="plus" onClick={() => openEntityEditor('new')}>Новая сущность</Button></div><div className="campaign-local-library__search"><Icon name="search" size={17} /><input value={entityQuery} aria-label="Поиск по библиотеке" placeholder="Найти по названию или тегу…" onChange={(event) => setEntityQuery(event.target.value)} /></div>{visibleEntities.length ? <div className="campaign-local-library__grid">{visibleEntities.map((entity) => <article key={entity.id}><span className="panel-kicker">{ENTITY_LABEL[entity.type]}</span><h3>{entity.name}</h3><p>{entity.description || 'Описание пока не добавлено.'}</p><footer><div>{entity.tags.map((tag) => <Badge size="sm" key={tag}>#{tag}</Badge>)}</div><Button size="sm" icon="pencil" onClick={() => openEntityEditor(entity)}>Редактировать</Button></footer></article>)}</div> : <EmptyState icon="library" title={campaign.entities.length ? 'Ничего не найдено' : 'Библиотека пока пуста'} hint={campaign.entities.length ? 'Измените поисковый запрос.' : 'Создайте первого персонажа, место или важный предмет.'} action={!campaign.entities.length ? <Button variant="primary" icon="plus" onClick={() => openEntityEditor('new')}>Создать сущность</Button> : undefined} />}</section>}
    {section === 'map' && <section className="campaign-section campaign-relation-map"><div className="panel-heading"><div><span className="panel-kicker">Карта ведущего</span><h2>Связи мира</h2><p>Кто с кем связан и что об этом знают игроки.</p></div><Button variant="primary" icon="plus" disabled={campaign.entities.length < 2} onClick={() => openRelationEditor('new')}>Новая связь</Button></div>{campaign.entities.length < 2 ? <EmptyState icon="share-2" title="Нужно хотя бы две сущности" hint="Добавьте их в библиотеку, и здесь можно будет связать персонажей, места и фракции." action={<Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/library`)}>Открыть библиотеку</Button>} /> : <><div className="campaign-relation-map__filters" aria-label="Видимость связей">{([['all', 'Все'], ['master', 'Только ведущим'], ['public', 'Для игроков']] as const).map(([value, label]) => <button key={value} className={relationVisibility === value ? 'active' : ''} onClick={() => setRelationVisibility(value)}>{label}</button>)}</div>{visibleRelations.length ? <div className="campaign-relation-map__list">{visibleRelations.map((relation) => <article key={relation.id}><div className="campaign-relation-map__nodes"><strong>{entityName(relation.fromId)}</strong><span><i />{relation.label}<i /></span><strong>{entityName(relation.toId)}</strong></div><footer><Badge tone={relation.visibility === 'master' ? 'warning' : 'success'} size="sm">{relation.visibility === 'master' ? 'Только ведущим' : 'Для игроков'}</Badge><Button size="sm" icon="pencil" onClick={() => openRelationEditor(relation)}>Редактировать</Button></footer></article>)}</div> : <EmptyState icon="share-2" title="Связей пока нет" hint="Соедините две сущности и подпишите, что между ними происходит." action={<Button variant="primary" icon="plus" onClick={() => openRelationEditor('new')}>Добавить связь</Button>} />}</>}</section>}
    {section === 'session' && <section className="campaign-section campaign-session-prep"><header className="panel-heading"><div><span className="panel-kicker">Сессия 01 · {campaign.firstSessionStatus === 'ready' ? 'готова' : 'черновик'}</span><h2>{campaign.firstSessionTitle}</h2></div><div className="row"><Badge tone={campaign.firstSessionStatus === 'ready' ? 'success' : 'warning'}>{campaign.firstSessionStatus === 'ready' ? 'Готова к игре' : 'Подготовка'}</Badge><Button icon="pencil" onClick={openSessionEditor}>Параметры</Button></div></header><div className="campaign-session-prep__summary"><article><span>Цель сессии</span><p>{campaign.firstSessionObjective || 'Цель пока не сформулирована.'}</p></article><article><span>Вступительная сцена</span><p>{campaign.firstSessionOpening || 'Вступление пока не подготовлено.'}</p></article></div><div className="campaign-session-prep__scenes"><div className="panel-heading"><div><span className="panel-kicker">Порядок игры</span><h3>Сцены и опорные моменты</h3></div><Button icon="plus" onClick={() => openSceneEditor('new')}>Добавить сцену</Button></div>{campaign.firstSessionScenes.length ? <ol>{campaign.firstSessionScenes.map((scene, index) => <li key={scene.id}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{scene.title}</strong><p>{scene.purpose || 'Без дополнительной заметки.'}</p></div><Button size="sm" icon="pencil" aria-label={`Редактировать сцену: ${scene.title}`} onClick={() => openSceneEditor(scene)} /></li>)}</ol> : <EmptyState icon="list-checks" title="План пока пуст" hint="Добавьте основные сцены или моменты, которые важно не потерять во время игры." action={<Button variant="primary" icon="plus" onClick={() => openSceneEditor('new')}>Добавить первую сцену</Button>} />}</div><footer className="campaign-session-prep__footer"><div><strong>{sessionPrepared ? 'Минимальный план готов' : 'Для готовности нужны цель, вступление и хотя бы одна сцена'}</strong><span>{campaign.firstSessionScenes.length} сцен в плане</span></div><Button variant="primary" icon="check" disabled={!sessionPrepared} onClick={() => persist({ ...campaign, firstSessionStatus: campaign.firstSessionStatus === 'ready' ? 'draft' : 'ready' })}>{campaign.firstSessionStatus === 'ready' ? 'Вернуть в подготовку' : 'Отметить готовой'}</Button></footer></section>}
    {editor === 'campaign' && <Editor title="Редактировать кампанию" close={() => setEditor(null)}><label htmlFor="local-edit-name">Название<input id="local-edit-name" autoFocus value={details.name} onChange={(e) => setDetails({ ...details, name: e.target.value })} /></label><label htmlFor="local-edit-idea">Короткая идея<textarea id="local-edit-idea" rows={4} value={details.idea} onChange={(e) => setDetails({ ...details, idea: e.target.value })} /></label><div className="control-form__row"><label htmlFor="local-edit-time">Текущее время<input id="local-edit-time" value={details.activeTime} onChange={(e) => setDetails({ ...details, activeTime: e.target.value })} /></label><label htmlFor="local-edit-masters">Ведущие<input id="local-edit-masters" value={details.masters} onChange={(e) => setDetails({ ...details, masters: e.target.value })} /></label></div><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!details.name.trim()} onClick={saveCampaign}>Сохранить</Button></footer></Editor>}
    {editor === 'session' && <Editor title="Редактировать сессию" close={() => setEditor(null)}><label htmlFor="local-session-name">Название<input id="local-session-name" autoFocus value={sessionTitle} onChange={(e) => setSessionTitle(e.target.value)} /></label><div className="control-form__row"><label htmlFor="local-session-master">Ответственный ведущий<input id="local-session-master" value={sessionMeta.master} onChange={(e) => setSessionMeta({ ...sessionMeta, master: e.target.value })} /></label><label htmlFor="local-session-time">Внутриигровое время<input id="local-session-time" value={sessionMeta.inGameTime} onChange={(e) => setSessionMeta({ ...sessionMeta, inGameTime: e.target.value })} /></label></div><label htmlFor="local-session-arc">Сюжетная линия<select id="local-session-arc" value={sessionMeta.arcId} onChange={(e) => setSessionMeta({ ...sessionMeta, arcId: e.target.value })}><option value="">Без привязки</option>{campaign.storyArcs.map((arc) => <option key={arc.id} value={arc.id}>{arc.title}</option>)}</select></label><label htmlFor="local-session-idea">Идея сессии<textarea id="local-session-idea" rows={2} value={sessionMeta.idea} placeholder="О чём эта игра?" onChange={(e) => setSessionMeta({ ...sessionMeta, idea: e.target.value })} /></label><label htmlFor="local-session-objective">Цель сессии<textarea id="local-session-objective" rows={3} value={sessionObjective} placeholder="Что должно измениться к концу игры?" onChange={(e) => setSessionObjective(e.target.value)} /></label><label htmlFor="local-session-opening">Стартовая ситуация<textarea id="local-session-opening" rows={3} value={sessionOpening} placeholder="С чего начинается игра?" onChange={(e) => setSessionOpening(e.target.value)} /></label><p className="muted">Сессия остаётся черновиком, пока вы явно не отметите её готовой.</p><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!sessionTitle.trim()} onClick={saveSession}>Сохранить</Button></footer></Editor>}
    {sceneEditor && <Editor title={sceneEditor === 'new' ? 'Новая сцена' : 'Редактировать сцену'} close={() => setSceneEditor(null)}><label htmlFor="scene-title">Название<input id="scene-title" autoFocus value={sceneDraft.title} placeholder="Встреча у восточных ворот" onChange={(event) => setSceneDraft({ ...sceneDraft, title: event.target.value })} /></label><label htmlFor="scene-purpose">Задача или заметка<textarea id="scene-purpose" rows={4} value={sceneDraft.purpose} placeholder="Что здесь должно произойти или стать понятно?" onChange={(event) => setSceneDraft({ ...sceneDraft, purpose: event.target.value })} /></label><footer>{sceneEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, firstSessionScenes: campaign.firstSessionScenes.filter((scene) => scene.id !== sceneEditor.id), firstSessionStatus: 'draft' }); setSceneEditor(null) }}>Удалить</Button>}<Button onClick={() => setSceneEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!sceneDraft.title.trim()} onClick={saveScene}>Сохранить</Button></footer></Editor>}
    {entityEditor && <Editor title={entityEditor === 'new' ? 'Новая сущность' : 'Редактировать сущность'} close={() => setEntityEditor(null)}><label htmlFor="local-entity-type">Тип<Select id="local-entity-type" value={entityDraft.type} onChange={(event) => setEntityDraft({ ...entityDraft, type: event.target.value as LocalCampaignEntityType })}>{ENTITY_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</Select></label><label htmlFor="local-entity-name">Название<input id="local-entity-name" autoFocus value={entityDraft.name} onChange={(event) => setEntityDraft({ ...entityDraft, name: event.target.value })} /></label><label htmlFor="local-entity-description">Рабочее описание<textarea id="local-entity-description" rows={4} value={entityDraft.description} onChange={(event) => setEntityDraft({ ...entityDraft, description: event.target.value })} /></label><label htmlFor="local-entity-tags">Теги<input id="local-entity-tags" value={entityDraft.tags.join(', ')} placeholder="важное, первая сессия" onChange={(event) => setEntityDraft({ ...entityDraft, tags: event.target.value.split(',') })} /></label><footer>{entityEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, entities: campaign.entities.filter((item) => item.id !== entityEditor.id), relations: campaign.relations.filter((relation) => relation.fromId !== entityEditor.id && relation.toId !== entityEditor.id) }); setEntityEditor(null) }}>Удалить</Button>}<Button onClick={() => setEntityEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!entityDraft.name.trim()} onClick={saveEntity}>Сохранить</Button></footer></Editor>}
    {relationEditor && <Editor title={relationEditor === 'new' ? 'Новая связь' : 'Редактировать связь'} close={() => setRelationEditor(null)}><div className="campaign-relation-form"><label htmlFor="relation-from">От<select id="relation-from" value={relationDraft.fromId} onChange={(event) => setRelationDraft({ ...relationDraft, fromId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label htmlFor="relation-to">К кому<select id="relation-to" value={relationDraft.toId} onChange={(event) => setRelationDraft({ ...relationDraft, toId: event.target.value })}>{campaign.entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label></div><label htmlFor="relation-label">Смысл связи<input id="relation-label" autoFocus value={relationDraft.label} placeholder="доверяет, преследует, хранит тайну…" onChange={(event) => setRelationDraft({ ...relationDraft, label: event.target.value })} /></label><label htmlFor="relation-visibility">Видимость<select id="relation-visibility" value={relationDraft.visibility} onChange={(event) => setRelationDraft({ ...relationDraft, visibility: event.target.value as 'master' | 'public' })}><option value="master">Только ведущим</option><option value="public">Для игроков</option></select></label>{relationDraft.fromId === relationDraft.toId && <p className="local-session-error">Выберите две разные сущности.</p>}<footer>{relationEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, relations: campaign.relations.filter((item) => item.id !== relationEditor.id) }); setRelationEditor(null) }}>Удалить</Button>}<Button onClick={() => setRelationEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!relationDraft.label.trim() || relationDraft.fromId === relationDraft.toId} onClick={saveRelation}>Сохранить</Button></footer></Editor>}
    {arcEditor && <Editor title={arcEditor === 'new' ? 'Новая сюжетная линия' : 'Редактировать сюжетную линию'} close={() => setArcEditor(null)}><label htmlFor="arc-title">Название<input id="arc-title" autoFocus value={arcDraft.title} placeholder="Договор с красной луной" onChange={(event) => setArcDraft({ ...arcDraft, title: event.target.value })} /></label><label htmlFor="arc-direction">Куда движется линия<textarea id="arc-direction" rows={3} value={arcDraft.direction} placeholder="Что произойдёт без вмешательства героев?" onChange={(event) => setArcDraft({ ...arcDraft, direction: event.target.value })} /></label><label htmlFor="arc-stakes">Ставки<textarea id="arc-stakes" rows={3} value={arcDraft.stakes} placeholder="Что можно потерять или приобрести?" onChange={(event) => setArcDraft({ ...arcDraft, stakes: event.target.value })} /></label><div className="campaign-arc-form__row"><label htmlFor="arc-status">Состояние<select id="arc-status" value={arcDraft.status} onChange={(event) => setArcDraft({ ...arcDraft, status: event.target.value as LocalStoryArc['status'] })}><option value="planned">Замысел</option><option value="active">В игре</option><option value="resolved">Завершено</option></select></label><label htmlFor="arc-progress">Прогресс · {arcDraft.progress}%<input id="arc-progress" type="range" min="0" max="100" step="10" value={arcDraft.progress} onChange={(event) => setArcDraft({ ...arcDraft, progress: Number(event.target.value) })} /></label></div><footer>{arcEditor !== 'new' && <Button tone="danger" onClick={() => { persist({ ...campaign, storyArcs: campaign.storyArcs.filter((item) => item.id !== arcEditor.id) }); setArcEditor(null) }}>Удалить</Button>}<Button onClick={() => setArcEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!arcDraft.title.trim()} onClick={saveArc}>Сохранить</Button></footer></Editor>}
    {section === 'session' && <LocalSessionContext campaign={campaign} persist={persist} />}
    {section === 'review' && <LocalSessionReview campaign={campaign} persist={persist} />}
  </main>

  return <main className="new-campaign-room"><header className="new-campaign-room__topbar"><Link to="/"><Icon name="arrow-left" size={16} /> Все кампании</Link><Badge tone="neutral" dot>Сохранено в браузере</Badge></header><section className="new-campaign-room__hero"><div><span className="panel-kicker">Новая локальная кампания</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><div className="new-campaign-room__readiness"><span>Первичная настройка</span><strong>{Number(Boolean(campaign.firstSessionTitle)) + Number(campaign.notes.length > 0)} / 2</strong></div></section><div className="new-campaign-room__layout"><section className="new-campaign-room__main">{!campaign.notes.length ? <EmptyState icon="book-open" title="Мир пока пуст" hint="Запишите первый факт, персонажа или место." action={<Capture value={note} setValue={setNote} add={addNote} />} /> : <><div className="panel-heading"><div><span className="panel-kicker">Первые опорные точки</span><h2>Заметки кампании</h2></div></div><ol className="new-campaign-room__notes">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></li>)}</ol><Capture value={note} setValue={setNote} add={addNote} /></>}</section><aside className="new-campaign-room__setup"><span className="panel-kicker">Быстрый старт</span><h2>Подготовьте первую игру</h2><label htmlFor="first-session">Название первой сессии<input id="first-session" value={sessionTitle} placeholder="Встреча у старых ворот" onChange={(e) => setSessionTitle(e.target.value)} /></label><Button variant="primary" block disabled={!sessionTitle.trim()} onClick={saveSession}>Создать сессию и открыть дашборд</Button><div className="new-campaign-room__steps"><span className={campaign.notes.length ? 'done' : ''}><Icon name={campaign.notes.length ? 'check' : 'circle'} size={16} /> Добавить опорную точку</span><span><Icon name="circle" size={16} /> Создать первую сессию</span></div></aside></div><p className="local-session-footnote"><Icon name="hard-drive" size={14} /> После выполнения двух шагов автоматически откроется дашборд кампании.</p></main>
}

function CampaignOverview({ campaign, persist, navigate }: { campaign: LocalCampaignRecord; persist: (next: LocalCampaignRecord) => void; navigate: (to: string) => void }) {
  const [capture, setCapture] = useState('')
  const sessionStatus = campaign.firstSessionStatus === 'completed' ? 'Завершена' : campaign.firstSessionStatus === 'active' ? 'Идёт сейчас' : campaign.firstSessionStatus === 'ready' ? 'Готова' : 'Подготовка'
  const nextPath = campaign.firstSessionStatus === 'completed' ? 'review' : campaign.firstSessionStatus === 'active' ? 'play' : 'session'
  const nextLabel = nextPath === 'review' ? 'Разобрать сессию' : nextPath === 'play' ? 'Открыть игровой стол' : 'Открыть сессию'
  const activeArcs = campaign.storyArcs.filter((arc) => arc.status === 'active')
  const toggleTask = (id: string) => persist({ ...campaign, tasks: campaign.tasks.map((task) => task.id === id ? { ...task, done: !task.done } : task) })
  const addCapture = () => { const text = capture.trim(); if (!text) return; persist({ ...campaign, inbox: [...campaign.inbox, { id: `inbox-${crypto.randomUUID()}`, text, tags: [], createdAt: new Date().toISOString() }] }); setCapture('') }
  return <>
    <section className="target-dashboard__session"><div><span className="panel-kicker">Текущая сессия · {sessionStatus}</span><h2>{campaign.firstSessionTitle}</h2><p>{campaign.firstSessionObjective || 'Добавьте цель сессии, чтобы зафиксировать ожидаемый результат игры.'}</p></div><div className="target-dashboard__session-action"><Badge tone={campaign.firstSessionStatus === 'completed' ? 'neutral' : 'warning'} dot>{sessionStatus}</Badge><Button variant="primary" icon="clapperboard" onClick={() => navigate(`/local/campaign/${campaign.id}/${nextPath}`)}>{nextLabel}</Button></div></section>
    <div className="target-dashboard__grid local-dashboard-grid">
      <Card className="target-panel target-panel--wide"><div className="panel-heading"><div><span className="panel-kicker">Движение кампании</span><h2 className="section-title">Активные линии</h2></div><Button onClick={() => navigate(`/local/campaign/${campaign.id}/arcs`)}>{activeArcs.length} в игре</Button></div><div className="target-lines">{activeArcs.length ? activeArcs.map((arc) => <article key={arc.id}><div><Badge tone="accent" size="sm">В игре · {arc.progress}%</Badge><h3>{arc.title}</h3><p>{arc.direction || 'Направление пока не задано.'}</p></div><strong>{arc.stakes || 'Ставки не определены'}</strong></article>) : <button className="local-dashboard-empty" onClick={() => navigate(`/local/campaign/${campaign.id}/arcs`)}><Icon name="plus" size={18} /> Добавить первую активную линию</button>}</div></Card>
      <Card className="target-panel"><div className="panel-heading"><div><span className="panel-kicker">Давление</span><h2 className="section-title">Часы</h2></div><Button size="sm" onClick={() => navigate(`/local/campaign/${campaign.id}/control`)}>Все</Button></div>{campaign.clocks.length ? campaign.clocks.slice(0, 3).map((clock) => <div className="target-clock" key={clock.id}><div className="row"><strong>{clock.title}</strong><span className="mb-data">{clock.value}/{clock.segments}</span></div><div className="target-clock__track"><span style={{ width: `${(clock.value / clock.segments) * 100}%` }} /></div><small>{clock.visibility === 'public' ? 'Можно показать игрокам' : 'Только ведущим'}</small></div>) : <button className="local-dashboard-empty" onClick={() => navigate(`/local/campaign/${campaign.id}/control`)}><Icon name="plus" size={18} /> Создать часы</button>}</Card>
      <Card className="target-panel"><div className="panel-heading"><div><span className="panel-kicker">Знание</span><h2 className="section-title">Секреты</h2></div><span className="panel-state">{campaign.secrets.filter((secret) => secret.status === 'hidden').length} скрыто</span></div>{campaign.secrets.length ? campaign.secrets.slice(0, 2).map((secret) => <article className="target-secret" key={secret.id}><Badge tone="warning" icon="shield" size="sm">{secret.status === 'hidden' ? 'Не раскрыт' : 'Изменён'}</Badge><h3>{secret.title}</h3><p>{secret.truth}</p><small>{secret.publicVersion ? `Для игроков: ${secret.publicVersion}` : 'Публичная версия не подготовлена'}</small></article>) : <button className="local-dashboard-empty" onClick={() => navigate(`/local/campaign/${campaign.id}/control`)}><Icon name="plus" size={18} /> Добавить секрет</button>}</Card>
      <Card className="target-panel"><div className="panel-heading"><div><span className="panel-kicker">Личное</span><h2 className="section-title">Список ведущего</h2></div><span className="panel-state">{campaign.tasks.filter((task) => !task.done).length} открыто</span></div>{campaign.tasks.length ? <ul className="target-checklist">{campaign.tasks.slice(0, 5).map((task) => <li key={task.id}><input id={`overview-${task.id}`} type="checkbox" checked={task.done} onChange={() => toggleTask(task.id)} /><label htmlFor={`overview-${task.id}`}>{task.text}</label><Badge tone={task.done ? 'neutral' : 'accent'} size="sm">{task.done ? 'готово' : task.source === 'inbox' ? 'входящие' : 'дело'}</Badge></li>)}</ul> : <button className="local-dashboard-empty" onClick={() => navigate(`/local/campaign/${campaign.id}/control`)}><Icon name="plus" size={18} /> Добавить задачу</button>}</Card>
      <Card className="target-panel"><div className="panel-heading"><div><span className="panel-kicker">Быстрая запись</span><h2 className="section-title">Входящие</h2></div><span className="panel-state">{campaign.inbox.length}</span></div><div className="target-capture"><input aria-label="Быстрая запись" value={capture} placeholder="Запишите идею, не разбирая её…" onChange={(event) => setCapture(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') addCapture() }} /><Button variant="primary" icon="plus" disabled={!capture.trim()} onClick={addCapture}>Записать</Button></div><ol className="target-inbox">{campaign.inbox.slice(-3).reverse().map((item) => <li key={item.id}><span>{item.text}</span>{item.tags[0] && <Badge tone="neutral" size="sm">{item.tags[0]}</Badge>}</li>)}</ol></Card>
    </div><p className="local-session-footnote"><Icon name="hard-drive" size={14} /> Все изменения сохранены в браузере. Интеграции отключены.</p>
  </>
}

const ARC_COLUMNS: Array<{ status: LocalStoryArc['status']; label: string; hint: string }> = [
  { status: 'planned', label: 'Замысел', hint: 'Линии, которые ещё не вышли на сцену' },
  { status: 'active', label: 'В игре', hint: 'То, что прямо сейчас меняет мир' },
  { status: 'resolved', label: 'Завершено', hint: 'Линии с зафиксированным исходом' },
]

function StoryArcsBoard({ arcs, openEditor }: { arcs: LocalStoryArc[]; openEditor: (arc: LocalStoryArc | 'new') => void }) {
  return <section className="campaign-section campaign-arcs"><header className="panel-heading"><div><span className="panel-kicker">Драматургическая карта</span><h2>Сюжетные линии</h2><p>Направление истории, ставки и текущее состояние — без жёсткого сценария.</p></div><Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Новая линия</Button></header><div className="campaign-arcs__summary"><span><strong>{arcs.filter((arc) => arc.status === 'active').length}</strong> в игре</span><span><strong>{arcs.filter((arc) => arc.progress >= 70 && arc.status !== 'resolved').length}</strong> близко к развязке</span><span><strong>{arcs.length}</strong> всего</span></div>{arcs.length ? <div className="campaign-arcs__board">{ARC_COLUMNS.map((column) => { const items = arcs.filter((arc) => arc.status === column.status); return <section key={column.status} data-status={column.status}><header><div><h3>{column.label}</h3><p>{column.hint}</p></div><span>{items.length}</span></header><div>{items.map((arc) => <article key={arc.id}><div className="campaign-arc__title"><Icon name="waypoints" size={17} /><h4>{arc.title}</h4><Button size="sm" icon="pencil" aria-label={`Редактировать линию: ${arc.title}`} onClick={() => openEditor(arc)} /></div><p>{arc.direction || 'Направление пока не задано.'}</p><div className="campaign-arc__stakes"><span>Ставки</span><strong>{arc.stakes || 'Не определены'}</strong></div><div className="campaign-arc__progress"><div><span>Прогресс</span><strong>{arc.progress}%</strong></div><i><span style={{ width: `${arc.progress}%` }} /></i></div></article>)}</div></section> })}</div> : <EmptyState icon="waypoints" title="Сюжетных линий пока нет" hint="Добавьте первое развивающееся противоречие: куда оно движется и что поставлено на карту." action={<Button variant="primary" icon="plus" onClick={() => openEditor('new')}>Создать первую линию</Button>} />}</section>
}

function Capture({ value, setValue, add, label = 'Добавить' }: { value: string; setValue: (value: string) => void; add: () => void; label?: string }) { return <div className="new-campaign-room__capture"><input value={value} aria-label="Новая опорная точка" placeholder="Добавить опорную точку…" onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') add() }} /><Button icon={label === 'Добавить' ? 'plus' : 'check'} disabled={!value.trim()} onClick={add}>{label}</Button></div> }
function Editor({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(e) => { if (e.currentTarget === e.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><span className="panel-kicker">Локальные параметры</span><h2>{title}</h2>{children}</section></div> }
