import { useEffect, useState, type ReactNode } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Badge, Button, EmptyState, Icon } from '../ds'
import { localCampaignCatalog, type LocalCampaignRecord } from '../fixtures/localCampaignCatalog'

export function LocalNewCampaignPage() {
  const { campaignId = '', section = 'overview' } = useParams()
  const navigate = useNavigate()
  const initial = localCampaignCatalog.find(campaignId)
  const [campaign, setCampaign] = useState(initial)
  const [note, setNote] = useState('')
  const [sessionTitle, setSessionTitle] = useState(initial?.firstSessionTitle ?? '')
  const [sessionObjective, setSessionObjective] = useState(initial?.firstSessionObjective ?? '')
  const [editingNote, setEditingNote] = useState<number | null>(null)
  const [editor, setEditor] = useState<'campaign' | 'session' | null>(null)
  const [details, setDetails] = useState({ name: initial?.name ?? '', idea: initial?.idea ?? '', activeTime: initial?.activeTime ?? '' })
  useEffect(() => { if (!editor) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setEditor(null) }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [editor])
  if (!campaign) return <Navigate to="/" replace />
  const persist = (next: LocalCampaignRecord) => setCampaign(localCampaignCatalog.update(next))
  const addNote = () => { const text = note.trim(); if (!text) return; persist({ ...campaign, notes: [...campaign.notes, text] }); setNote('') }
  const saveSession = () => { if (!sessionTitle.trim()) return; persist({ ...campaign, firstSessionTitle: sessionTitle.trim(), firstSessionObjective: sessionObjective.trim(), sessions: 1 }); setEditor(null) }
  const saveCampaign = () => { if (!details.name.trim()) return; persist({ ...campaign, name: details.name.trim(), idea: details.idea.trim(), activeTime: details.activeTime.trim() || 'Время ещё не задано' }); setEditor(null) }
  const ready = campaign.notes.length > 0 && Boolean(campaign.firstSessionTitle)

  const openSessionEditor = () => { setSessionTitle(campaign.firstSessionTitle); setSessionObjective(campaign.firstSessionObjective); setEditor('session') }
  const saveNote = () => { if (editingNote === null || !note.trim()) return; const notes = [...campaign.notes]; notes[editingNote] = note.trim(); persist({ ...campaign, notes }); setNote(''); setEditingNote(null) }
  const removeNote = (index: number) => persist({ ...campaign, notes: campaign.notes.filter((_, noteIndex) => noteIndex !== index) })

  if (ready) return <main className="created-dashboard">
    <header className="new-campaign-room__topbar"><Link to="/"><Icon name="arrow-left" size={16} /> Все кампании</Link><div><Badge tone="success" dot>Основа готова</Badge><Badge tone="neutral">Сохранено в браузере</Badge></div></header>
    <section className="created-dashboard__hero"><div><span className="panel-kicker">Рабочее пространство кампании</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><Button icon="pencil" onClick={() => { setDetails({ name: campaign.name, idea: campaign.idea, activeTime: campaign.activeTime }); setEditor('campaign') }}>Настройки кампании</Button></section>
    <nav className="campaign-section-nav" aria-label="Разделы кампании"><Link className={section === 'overview' ? 'active' : ''} to={`/local/campaign/${campaign.id}/overview`}><Icon name="layout-dashboard" size={17} />Обзор</Link><Link className={section === 'world' ? 'active' : ''} to={`/local/campaign/${campaign.id}/world`}><Icon name="book-open" size={17} />Мир <span>{campaign.notes.length}</span></Link><Link className={section === 'session' ? 'active' : ''} to={`/local/campaign/${campaign.id}/session`}><Icon name="calendar" size={17} />Сессия</Link></nav>
    {section === 'overview' && <><div className="campaign-next-action"><div><span className="panel-kicker">Следующее действие</span><h2>Подготовить «{campaign.firstSessionTitle}»</h2><p>{campaign.firstSessionObjective || 'Добавьте цель сессии, чтобы зафиксировать ожидаемый результат игры.'}</p></div><Button variant="primary" icon="arrow-right" onClick={() => navigate(`/local/campaign/${campaign.id}/session`)}>Открыть подготовку</Button></div><div className="created-dashboard__grid"><section><div className="panel-heading"><div><span className="panel-kicker">Мир кампании</span><h2>Последние опорные точки</h2></div><Button onClick={() => navigate(`/local/campaign/${campaign.id}/world`)}>Открыть мир</Button></div><ol>{campaign.notes.slice(0, 4).map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></li>)}</ol></section><aside><span className="panel-kicker">Состояние кампании</span><dl><div><dt>Текущее время</dt><dd>{campaign.activeTime}</dd></div><div><dt>Ведущий</dt><dd>{campaign.masters}</dd></div><div><dt>Сессий</dt><dd>{campaign.sessions}</dd></div></dl><p><Icon name="hard-drive" size={15} /> Изменения сохраняются локально.</p></aside></div></>}
    {section === 'world' && <section className="campaign-section"><div className="panel-heading"><div><span className="panel-kicker">Контекст для подготовки</span><h2>Мир кампании</h2><p>Факты, места и персонажи, на которые можно опираться во время игры.</p></div><span className="panel-state">{campaign.notes.length}</span></div><ol className="campaign-world-list">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p><div><Button icon="pencil" aria-label={`Редактировать: ${item}`} onClick={() => { setEditingNote(index); setNote(item) }} /><Button icon="trash-2" aria-label={`Удалить: ${item}`} onClick={() => removeNote(index)} /></div></li>)}</ol><Capture value={note} setValue={setNote} add={editingNote === null ? addNote : saveNote} label={editingNote === null ? 'Добавить' : 'Сохранить'} />{editingNote !== null && <Button onClick={() => { setEditingNote(null); setNote('') }}>Отменить редактирование</Button>}</section>}
    {section === 'session' && <section className="campaign-section campaign-session-sheet"><div><div className="panel-heading"><div><span className="panel-kicker">Сессия 01 · черновик</span><h2>{campaign.firstSessionTitle}</h2></div><Badge tone="warning">Подготовка</Badge></div><div className="campaign-session-objective"><span>Цель сессии</span><p>{campaign.firstSessionObjective || 'Цель пока не сформулирована.'}</p></div></div><aside><span className="panel-kicker">Управление</span><p>Здесь меняются данные сессии. Запуск игры появится на следующем этапе рабочего потока.</p><Button variant="primary" block icon="pencil" onClick={openSessionEditor}>Редактировать сессию</Button></aside></section>}
    {editor === 'campaign' && <Editor title="Редактировать кампанию" close={() => setEditor(null)}><label htmlFor="local-edit-name">Название<input id="local-edit-name" autoFocus value={details.name} onChange={(e) => setDetails({ ...details, name: e.target.value })} /></label><label htmlFor="local-edit-idea">Короткая идея<textarea id="local-edit-idea" rows={4} value={details.idea} onChange={(e) => setDetails({ ...details, idea: e.target.value })} /></label><label htmlFor="local-edit-time">Текущее время<input id="local-edit-time" value={details.activeTime} onChange={(e) => setDetails({ ...details, activeTime: e.target.value })} /></label><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!details.name.trim()} onClick={saveCampaign}>Сохранить</Button></footer></Editor>}
    {editor === 'session' && <Editor title="Редактировать сессию" close={() => setEditor(null)}><label htmlFor="local-session-name">Название<input id="local-session-name" autoFocus value={sessionTitle} onChange={(e) => setSessionTitle(e.target.value)} /></label><label htmlFor="local-session-objective">Цель сессии<textarea id="local-session-objective" rows={4} value={sessionObjective} placeholder="Что должно измениться к концу игры?" onChange={(e) => setSessionObjective(e.target.value)} /></label><p className="muted">Сессия остаётся черновиком до явного начала игры.</p><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" icon="check" disabled={!sessionTitle.trim()} onClick={saveSession}>Сохранить</Button></footer></Editor>}
  </main>

  return <main className="new-campaign-room"><header className="new-campaign-room__topbar"><Link to="/"><Icon name="arrow-left" size={16} /> Все кампании</Link><Badge tone="neutral" dot>Сохранено в браузере</Badge></header><section className="new-campaign-room__hero"><div><span className="panel-kicker">Новая локальная кампания</span><h1>{campaign.name}</h1><p>{campaign.idea}</p></div><div className="new-campaign-room__readiness"><span>Первичная настройка</span><strong>{Number(Boolean(campaign.firstSessionTitle)) + Number(campaign.notes.length > 0)} / 2</strong></div></section><div className="new-campaign-room__layout"><section className="new-campaign-room__main">{!campaign.notes.length ? <EmptyState icon="book-open" title="Мир пока пуст" hint="Запишите первый факт, персонажа или место." action={<Capture value={note} setValue={setNote} add={addNote} />} /> : <><div className="panel-heading"><div><span className="panel-kicker">Первые опорные точки</span><h2>Заметки кампании</h2></div></div><ol className="new-campaign-room__notes">{campaign.notes.map((item, index) => <li key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></li>)}</ol><Capture value={note} setValue={setNote} add={addNote} /></>}</section><aside className="new-campaign-room__setup"><span className="panel-kicker">Быстрый старт</span><h2>Подготовьте первую игру</h2><label htmlFor="first-session">Название первой сессии<input id="first-session" value={sessionTitle} placeholder="Встреча у старых ворот" onChange={(e) => setSessionTitle(e.target.value)} /></label><Button variant="primary" block disabled={!sessionTitle.trim()} onClick={saveSession}>Создать сессию и открыть дашборд</Button><div className="new-campaign-room__steps"><span className={campaign.notes.length ? 'done' : ''}><Icon name={campaign.notes.length ? 'check' : 'circle'} size={16} /> Добавить опорную точку</span><span><Icon name="circle" size={16} /> Создать первую сессию</span></div></aside></div><p className="local-session-footnote"><Icon name="hard-drive" size={14} /> После выполнения двух шагов автоматически откроется дашборд кампании.</p></main>
}

function Capture({ value, setValue, add, label = 'Добавить' }: { value: string; setValue: (value: string) => void; add: () => void; label?: string }) { return <div className="new-campaign-room__capture"><input value={value} aria-label="Новая опорная точка" placeholder="Добавить опорную точку…" onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') add() }} /><Button icon={label === 'Добавить' ? 'plus' : 'check'} disabled={!value.trim()} onClick={add}>{label}</Button></div> }
function Editor({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(e) => { if (e.currentTarget === e.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><span className="panel-kicker">Локальные параметры</span><h2>{title}</h2>{children}</section></div> }
