import { useMemo, useState, type ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Badge, Button, EmptyState, Icon, Select } from '../ds'
import { getLocalSessions, withLocalSessions, type LocalCampaignEntityType, type LocalCampaignRecord, type LocalSessionPlanItem, type LocalSessionPlanKind, type LocalSessionRecord } from '../fixtures/localCampaignCatalog'

type Props = { campaign: LocalCampaignRecord; persist: (next: LocalCampaignRecord) => void; mode?: 'plan' | 'play' | 'review' }
const priorities = [['required', 'Обязательно'], ['desired', 'Желательно'], ['useful', 'Полезно'], ['backup', 'Запас']] as const
const kinds: Array<[LocalSessionPlanKind, string]> = [['scene', 'Сцена'], ['idea', 'Идея'], ['goal', 'Цель'], ['event', 'Событие'], ['question', 'Вопрос'], ['secret', 'Секрет'], ['npc', 'NPC'], ['material', 'Материал'], ['note', 'Заметка'], ['consequence', 'Последствие']]
const statusLabel = { draft: 'Черновик', ready: 'Готова', active: 'Проводится', completed: 'Закрыта' } as const
const useStatus = [['prepared', 'Подготовлено'], ['current', 'Актуально'], ['used', 'Использовано'], ['skipped', 'Пропущено'], ['moved', 'Перенесено'], ['cancelled', 'Отменено']] as const
const blankSession = (number: number, master: string): LocalSessionRecord => ({ id: `session-${crypto.randomUUID()}`, number, title: '', status: 'draft', master, arcId: '', group: '', participants: '', inGameTime: '', timelinePosition: '', idea: '', focus: '', opening: '', lines: '', layers: '', systems: '', planItems: [], flows: [], log: [], reviewNotes: '', reviewStatus: 'draft', reviewDecisions: {}, createdAt: new Date().toISOString() })

export function LocalSessionsWorkspace({ campaign, persist, mode = 'plan' }: Props) {
  const navigate = useNavigate()
  const sessions = getLocalSessions(campaign)
  const initialId = campaign.activeSessionId && sessions.some((item) => item.id === campaign.activeSessionId) ? campaign.activeSessionId : sessions[0]?.id
  const [selectedId, setSelectedId] = useState(initialId ?? '')
  const selected = sessions.find((item) => item.id === selectedId) ?? sessions[0]
  const [editor, setEditor] = useState<LocalSessionRecord | null>(null)
  const [quickText, setQuickText] = useState('')
  const [quickKind, setQuickKind] = useState<LocalSessionPlanKind>('scene')
  const [quickPriority, setQuickPriority] = useState<LocalSessionPlanItem['priority']>('desired')
  const [libraryOpen, setLibraryOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [liveText, setLiveText] = useState('')
  const linkedIds = useMemo(() => new Set(selected?.planItems.flatMap((item) => item.entityId ? [item.entityId] : []) ?? []), [selected])
  const updateSession = (next: LocalSessionRecord) => persist(withLocalSessions(campaign, sessions.map((item) => item.id === next.id ? next : item), next.id))
  const choose = (id: string) => { setSelectedId(id); persist(withLocalSessions(campaign, sessions, id)) }
  const create = () => setEditor(blankSession(Math.max(0, ...sessions.map((item) => item.number)) + 1, campaign.masters.split('+')[0]?.trim() || 'Сова'))
  const savePassport = () => { if (!editor?.title.trim()) return; const exists = sessions.some((item) => item.id === editor.id); const next = { ...editor, title: editor.title.trim() }; persist(withLocalSessions(campaign, exists ? sessions.map((item) => item.id === next.id ? next : item) : [...sessions, next], next.id)); setSelectedId(next.id); setEditor(null) }
  const addText = () => { const text = quickText.trim(); if (!text || !selected) return; updateSession({ ...selected, planItems: [...selected.planItems, { id: `plan-${crypto.randomUUID()}`, source: 'text', text, kind: quickKind, priority: quickPriority, status: 'prepared', role: '', alternative: '', note: '', origin: 'prepared' }] }); setQuickText('') }
  const attachEntity = (entityId: string) => { if (!selected) return; const entity = campaign.entities.find((item) => item.id === entityId); if (!entity) return; updateSession({ ...selected, planItems: [...selected.planItems, { id: `plan-${crypto.randomUUID()}`, source: 'library', entityId, text: entity.name, kind: entity.type === 'npc' ? 'npc' : entity.type === 'handout' || entity.type === 'map' ? 'material' : 'note', priority: quickPriority, status: 'prepared', role: '', alternative: '', note: '', origin: 'prepared' }] }) }
  const itemTitle = (item: LocalSessionPlanItem) => item.entityId ? campaign.entities.find((entity) => entity.id === item.entityId)?.name ?? item.text : item.text
  const patchItem = (id: string, patch: Partial<LocalSessionPlanItem>) => selected && updateSession({ ...selected, planItems: selected.planItems.map((item) => item.id === id ? { ...item, ...patch } : item) })
  const moveItem = (id: string, delta: number) => { if (!selected) return; const list = [...selected.planItems]; const at = list.findIndex((item) => item.id === id); const to = Math.max(0, Math.min(list.length - 1, at + delta)); if (at === to) return; const [item] = list.splice(at, 1); list.splice(to, 0, item); updateSession({ ...selected, planItems: list }) }
  const saveToLibrary = (item: LocalSessionPlanItem) => { if (!selected || item.source === 'library') return; const map: Partial<Record<LocalSessionPlanKind, LocalCampaignEntityType>> = { npc: 'npc', secret: 'note', material: 'handout', note: 'note', scene: 'note', idea: 'note', goal: 'note', event: 'note', question: 'note', consequence: 'note' }; const entityId = `entity-${crypto.randomUUID()}`; const entity = { id: entityId, type: map[item.kind] ?? 'note', name: item.text, description: item.note || `Создано из плана сессии №${selected.number}`, tags: ['из сессии'], visibility: 'master' as const, status: 'active' as const }; const nextSession = { ...selected, planItems: selected.planItems.map((current) => current.id === item.id ? { ...current, source: 'library' as const, entityId } : current) }; persist(withLocalSessions({ ...campaign, entities: [...campaign.entities, entity] }, sessions.map((current) => current.id === selected.id ? nextSession : current), selected.id)) }
  const addLive = () => { const text = liveText.trim(); if (!text || !selected) return; updateSession({ ...selected, log: [...selected.log, { id: `log-${crypto.randomUUID()}`, text, createdAt: new Date().toISOString() }] }); setLiveText('') }

  return <main className="sessions-workspace">
    <header className="sessions-workspace__top"><Link to={`/local/campaign/${campaign.id}/overview`}><Icon name="arrow-left" size={16} /> {campaign.name}</Link><nav><Link to={`/local/campaign/${campaign.id}/overview`}>Обзор</Link><Link className="active" to={`/local/campaign/${campaign.id}/session`}>Сессии</Link><Link to={`/local/campaign/${campaign.id}/library`}>Библиотека</Link></nav><Badge tone="neutral" dot>Локальные данные</Badge></header>
    <div className="sessions-workspace__body">
      <aside className="sessions-workspace__rail"><div className="panel-heading"><div><span className="panel-kicker">Кампания</span><h2>Сессии</h2></div><Button size="sm" icon="plus" onClick={create}>Новая</Button></div><div className="sessions-workspace__session-list">{sessions.map((session) => <button key={session.id} className={session.id === selected?.id ? 'active' : ''} onClick={() => choose(session.id)}><span>{String(session.number).padStart(2, '0')}</span><div><strong>{session.title}</strong><small>{statusLabel[session.status]} · {session.inGameTime || 'время не задано'}</small></div></button>)}</div>{!sessions.length && <EmptyState icon="clapperboard" title="Сессий пока нет" hint="Создайте первую или планируйте несколько заранее." action={<Button variant="primary" onClick={create}>Создать сессию</Button>} />}</aside>
      {selected && <section className="session-plan"><header className="session-plan__passport"><div><span className="panel-kicker">Сессия {String(selected.number).padStart(2, '0')} · {statusLabel[selected.status]}</span><h1>{selected.title}</h1><p>{selected.focus || selected.idea || 'Фокус пока не задан.'}</p></div><div className="session-plan__actions"><Button icon="pencil" onClick={() => setEditor(structuredClone(selected))}>Паспорт</Button>{selected.status === 'active' ? <Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/play`)}>Панель проведения</Button> : selected.status === 'completed' ? <Button variant="primary" onClick={() => navigate(`/local/campaign/${campaign.id}/review`)}>Разобрать</Button> : <Button variant="primary" icon="play" disabled={!selected.planItems.length} onClick={() => { updateSession({ ...selected, status: 'active' }); navigate(`/local/campaign/${campaign.id}/play`) }}>Начать</Button>}</div></header>
        <dl className="session-plan__meta"><div><dt>Мастер</dt><dd>{selected.master || 'Не назначен'}</dd></div><div><dt>Группа и участники</dt><dd>{[selected.group, selected.participants].filter(Boolean).join(' · ') || 'Не заданы'}</dd></div><div><dt>Время и шкала</dt><dd>{[selected.inGameTime, selected.timelinePosition].filter(Boolean).join(' · ') || 'Не заданы'}</dd></div><div><dt>Стартовая ситуация</dt><dd>{selected.opening || 'Не задана'}</dd></div></dl>
        <section className="session-plan__composer"><div className="row"><Select aria-label="Тип пункта плана" value={quickKind} onChange={(event) => setQuickKind(event.target.value as LocalSessionPlanKind)}>{kinds.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select aria-label="Приоритет пункта" value={quickPriority} onChange={(event) => setQuickPriority(event.target.value as LocalSessionPlanItem['priority'])}>{priorities.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div><input aria-label="Свободный текст пункта плана" value={quickText} placeholder="Сцена, идея, вопрос или любой свободный текст…" onChange={(event) => setQuickText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') addText() }} /><Button variant="primary" disabled={!quickText.trim()} onClick={addText}>Добавить текстом</Button><Button icon="library" onClick={() => setLibraryOpen(true)}>Из библиотеки</Button></section>
        <div className="session-plan__columns">{priorities.map(([priority, label]) => { const list = selected.planItems.filter((item) => item.priority === priority); return <section key={priority} data-priority={priority}><header><h2>{label}</h2><span>{list.length}</span></header>{list.map((item) => <article key={item.id}><div className="session-plan__item-main"><div className="row"><Badge size="sm" tone={item.source === 'library' ? 'accent' : 'neutral'}>{item.source === 'library' ? 'Библиотека' : 'Текст'}</Badge><Select aria-label={`Тип ${itemTitle(item)}`} value={item.kind} onChange={(event) => patchItem(item.id, { kind: event.target.value as LocalSessionPlanKind })}>{kinds.map(([value, name]) => <option key={value} value={value}>{name}</option>)}</Select></div><h3>{itemTitle(item)}</h3><input value={item.note} aria-label={`Заметка ${itemTitle(item)}`} placeholder="Локальная заметка, условие или роль…" onChange={(event) => patchItem(item.id, { note: event.target.value })} /></div><div className="session-plan__item-controls"><Select aria-label={`Статус ${itemTitle(item)}`} value={item.status} onChange={(event) => patchItem(item.id, { status: event.target.value as LocalSessionPlanItem['status'] })}>{useStatus.map(([value, name]) => <option key={value} value={value}>{name}</option>)}</Select><div className="row"><Button size="sm" aria-label="Выше" onClick={() => moveItem(item.id, -1)}>↑</Button><Button size="sm" aria-label="Ниже" onClick={() => moveItem(item.id, 1)}>↓</Button>{item.source === 'text' && <Button size="sm" icon="library" onClick={() => saveToLibrary(item)}>В библиотеку</Button>}<Button size="sm" tone="danger" icon="trash-2" aria-label={`Убрать ${itemTitle(item)} из сессии`} onClick={() => updateSession({ ...selected, planItems: selected.planItems.filter((current) => current.id !== item.id) })} /></div></div></article>)}{!list.length && <p className="session-plan__empty">Пока пусто</p>}</section> })}</div>
        {(mode === 'play' || selected.status === 'active') && <aside className="session-live-panel"><header><div><span className="panel-kicker">Проведение на этом же плане</span><h2>Живой журнал</h2></div><Button tone="danger" icon="check" onClick={() => updateSession({ ...selected, status: 'completed' })}>Закрыть сессию</Button></header><div className="session-live-panel__capture"><input value={liveText} placeholder="Что случилось фактически…" aria-label="Запись живого журнала" onChange={(event) => setLiveText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') addLive() }} /><Button variant="primary" disabled={!liveText.trim()} onClick={addLive}>Сохранить момент</Button></div><ol>{[...selected.log].reverse().map((entry) => <li key={entry.id}><time>{new Date(entry.createdAt).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}</time><span>{entry.text}</span></li>)}</ol></aside>}
        {(mode === 'review' || selected.status === 'completed') && <section className="session-review-panel"><header><div><span className="panel-kicker">Разбор можно дополнять позднее</span><h2>Итоги сессии</h2></div><div className="row"><Button icon="plus" onClick={create}>Предложить следующую</Button><Button variant="primary" icon="check" onClick={() => updateSession({ ...selected, reviewStatus: selected.reviewStatus === 'completed' ? 'draft' : 'completed' })}>{selected.reviewStatus === 'completed' ? 'Открыть разбор' : 'Завершить разбор'}</Button></div></header><label>Итоги, последствия и изменение времени<textarea rows={5} disabled={selected.reviewStatus === 'completed'} value={selected.reviewNotes} onChange={(event) => updateSession({ ...selected, reviewNotes: event.target.value })} /></label><div className="session-review-panel__unused">{selected.planItems.filter((item) => ['required', 'desired'].includes(item.priority) && !['used', 'cancelled'].includes(item.status)).map((item) => <label key={item.id}><span><strong>{itemTitle(item)}</strong><small>{item.priority === 'required' ? 'Обязательно' : 'Желательно'} · {item.status}</small></span><Select disabled={selected.reviewStatus === 'completed'} value={selected.reviewDecisions[item.id] ?? ''} onChange={(event) => updateSession({ ...selected, reviewDecisions: { ...selected.reviewDecisions, [item.id]: event.target.value as 'carry' | 'library' | 'cancel' | 'keep' } })}><option value="">Нужно решение</option><option value="carry">Перенести</option><option value="library">Вернуть только в библиотеку</option><option value="cancel">Отменить</option><option value="keep">Оставить неиспользованным</option></Select></label>)}</div></section>}
      </section>}
    </div>
    {editor && <Modal title={sessions.some((item) => item.id === editor.id) ? 'Паспорт сессии' : 'Новая сессия'} close={() => setEditor(null)}><div className="session-passport-form"><label>Название<input autoFocus value={editor.title} onChange={(event) => setEditor({ ...editor, title: event.target.value })} /></label><div className="control-form__row"><label>Номер<input type="number" min="1" value={editor.number} onChange={(event) => setEditor({ ...editor, number: Number(event.target.value) })} /></label><label>Статус<Select value={editor.status} onChange={(event) => setEditor({ ...editor, status: event.target.value as LocalSessionRecord['status'] })}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><label>Ответственный мастер<input value={editor.master} onChange={(event) => setEditor({ ...editor, master: event.target.value })} /></label></div><div className="control-form__row"><label>Основная группа<input value={editor.group} onChange={(event) => setEditor({ ...editor, group: event.target.value })} /></label><label>Герои и приглашённые<input value={editor.participants} onChange={(event) => setEditor({ ...editor, participants: event.target.value })} /></label></div><div className="control-form__row"><label>Арка<Select value={editor.arcId} onChange={(event) => setEditor({ ...editor, arcId: event.target.value })}><option value="">Без арки</option>{campaign.storyArcs.map((arc) => <option key={arc.id} value={arc.id}>{arc.title}</option>)}</Select></label><label>Внутриигровое время<input value={editor.inGameTime} onChange={(event) => setEditor({ ...editor, inGameTime: event.target.value })} /></label><label>Положение на шкале<input value={editor.timelinePosition} onChange={(event) => setEditor({ ...editor, timelinePosition: event.target.value })} /></label></div><label>Идея<textarea rows={2} value={editor.idea} onChange={(event) => setEditor({ ...editor, idea: event.target.value })} /></label><label>Цель, вопрос или тема<textarea rows={2} value={editor.focus} onChange={(event) => setEditor({ ...editor, focus: event.target.value })} /></label><label>Стартовая ситуация<textarea rows={2} value={editor.opening} onChange={(event) => setEditor({ ...editor, opening: event.target.value })} /></label><div className="control-form__row"><label>Связанные линии<input value={editor.lines} onChange={(event) => setEditor({ ...editor, lines: event.target.value })} /></label><label>Слои<input value={editor.layers} onChange={(event) => setEditor({ ...editor, layers: event.target.value })} /></label><label>Системы и миры<input value={editor.systems} onChange={(event) => setEditor({ ...editor, systems: event.target.value })} /></label></div></div><footer><Button onClick={() => setEditor(null)}>Отмена</Button><Button variant="primary" disabled={!editor.title.trim()} onClick={savePassport}>Сохранить</Button></footer></Modal>}
    {libraryOpen && <Modal title="Добавить из библиотеки" close={() => setLibraryOpen(false)}><div className="session-library-picker"><input autoFocus value={query} placeholder="Название или тег…" aria-label="Поиск в библиотеке для сессии" onChange={(event) => setQuery(event.target.value)} />{campaign.entities.filter((entity) => !linkedIds.has(entity.id) && `${entity.name} ${entity.tags.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map((entity) => <button key={entity.id} onClick={() => attachEntity(entity.id)}><div><span className="panel-kicker">{entity.type}</span><strong>{entity.name}</strong><small>{entity.description}</small></div><Icon name="plus" size={16} /></button>)}</div><footer><Button onClick={() => setLibraryOpen(false)}>Готово</Button></footer></Modal>}
  </main>
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(event) => { if (event.currentTarget === event.target) close() }}><section className="campaign-workspace__modal sessions-modal" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2>{children}</section></div> }
