import { useState, type ReactNode } from 'react'
import { Badge, Button, EmptyState, Icon, Select } from '../ds'
import type { LocalCampaignRecord, LocalSessionFlow, LocalSessionItem } from '../fixtures/localCampaignCatalog'

type Props = { campaign: LocalCampaignRecord; persist: (next: LocalCampaignRecord) => void }
const priorityLabels = { required: 'Обязательно', desired: 'Желательно', useful: 'Полезно', backup: 'Запас' } as const
const statusLabels = { prepared: 'Подготовлено', current: 'Актуально', used: 'Использовано', skipped: 'Пропущено', moved: 'Перенесено', cancelled: 'Отменено' } as const

export function LocalSessionContext({ campaign, persist }: Props) {
  const items = campaign.firstSessionItems ?? []
  const flows = campaign.firstSessionFlows ?? []
  const [view, setView] = useState<'items' | 'flows'>('items')
  const [query, setQuery] = useState('')
  const [picker, setPicker] = useState(false)
  const [flowEditor, setFlowEditor] = useState(false)
  const [editing, setEditing] = useState<LocalSessionItem | null>(null)
  const [flow, setFlow] = useState<Omit<LocalSessionFlow, 'id'>>({ fromItemId: '', toItemId: '', condition: '' })
  const linked = items.map((item) => ({ item, entity: campaign.entities.find((entity) => entity.id === item.entityId) })).filter((row) => row.entity)
  const available = campaign.entities.filter((entity) => !items.some((item) => item.entityId === entity.id) && `${entity.name} ${entity.type} ${entity.tags.join(' ')}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))
  const attach = (entityId: string) => persist({ ...campaign, firstSessionItems: [...items, { id: crypto.randomUUID(), entityId, role: '', priority: 'desired', status: 'prepared', alternative: '', note: '' }] })
  const update = (item: LocalSessionItem) => persist({ ...campaign, firstSessionItems: items.map((current) => current.id === item.id ? item : current) })
  const name = (itemId: string) => linked.find((row) => row.item.id === itemId)?.entity?.name ?? 'Удалённый элемент'
  const addFlow = () => { if (!flow.fromItemId || !flow.toItemId || flow.fromItemId === flow.toItemId) return; persist({ ...campaign, firstSessionFlows: [...flows, { ...flow, id: crypto.randomUUID() }] }); setFlowEditor(false) }

  return <section className="session-context">
    <header><div><span className="panel-kicker">Контекст сессии</span><h3>Библиотечные элементы и потоки</h3><p>Сцены остаются в плане выше. Здесь — переиспользуемые персонажи, места, материалы и связи этой сессии.</p></div><div className="session-context__actions"><div className="session-context__switch"><button className={view === 'items' ? 'active' : ''} onClick={() => setView('items')}>Подборка <span>{items.length}</span></button><button className={view === 'flows' ? 'active' : ''} onClick={() => setView('flows')}>Потоки <span>{flows.length}</span></button></div><Button icon="plus" onClick={() => setPicker(true)}>Добавить</Button></div></header>
    {view === 'items' && (linked.length ? <div className="session-context__list">{linked.map(({ item, entity }) => <article key={item.id}><div><div className="row"><Badge size="sm">{entity!.type}</Badge><Badge tone={item.priority === 'required' ? 'warning' : 'neutral'} size="sm">{priorityLabels[item.priority]}</Badge></div><h4>{entity!.name}</h4><p>{item.role || item.note || entity!.description || 'Роль в сессии не задана'}</p>{item.alternative && <small>Альтернатива: {item.alternative}</small>}</div><div><Badge tone={item.status === 'used' ? 'success' : 'accent'}>{statusLabels[item.status]}</Badge><Button size="sm" icon="pencil" onClick={() => setEditing(item)}>Настроить</Button></div></article>)}</div> : <EmptyState icon="library" title="Контекст ещё не собран" hint="Добавьте записи из библиотеки; сцены из плана при этом не исчезнут." action={<Button variant="primary" onClick={() => setPicker(true)}>Открыть библиотеку</Button>} />)}
    {view === 'flows' && <div className="session-context__flows"><div className="row"><p>Переходы связывают элементы условием, но не копируют карточки.</p><Button icon="plus" disabled={linked.length < 2} onClick={() => { setFlow({ fromItemId: linked[0]?.item.id ?? '', toItemId: linked[1]?.item.id ?? '', condition: '' }); setFlowEditor(true) }}>Новый поток</Button></div>{flows.map((entry) => <article key={entry.id}><strong>{name(entry.fromItemId)}</strong><span><Icon name="arrow-right" size={16} /> {entry.condition || 'далее'} <Icon name="arrow-right" size={16} /></span><strong>{name(entry.toItemId)}</strong><Button size="sm" tone="danger" icon="trash-2" aria-label="Удалить поток" onClick={() => persist({ ...campaign, firstSessionFlows: flows.filter((item) => item.id !== entry.id) })} /></article>)}</div>}
    {picker && <Modal title="Добавить из библиотеки" close={() => setPicker(false)}><div className="session-context__search"><Icon name="search" size={17} /><input autoFocus value={query} placeholder="Название, тип или тег…" aria-label="Поиск в библиотеке" onChange={(event) => setQuery(event.target.value)} /></div><div className="session-context__picker">{available.map((entity) => <button key={entity.id} onClick={() => attach(entity.id)}><span className="panel-kicker">{entity.type}</span><strong>{entity.name}</strong><small>{entity.description || 'Без описания'}</small><Icon name="plus" size={16} /></button>)}</div>{!available.length && <EmptyState icon="search" title="Ничего не найдено" hint={campaign.entities.length ? 'Измените запрос или все найденные объекты уже добавлены.' : 'Сначала создайте записи в библиотеке кампании.'} />}<footer><Button onClick={() => setPicker(false)}>Готово</Button></footer></Modal>}
    {editing && <Modal title={`Использование: ${campaign.entities.find((entity) => entity.id === editing.entityId)?.name ?? ''}`} close={() => setEditing(null)}><label>Роль в сессии<input value={editing.role} onChange={(event) => setEditing({ ...editing, role: event.target.value })} /></label><div className="control-form__row"><label>Приоритет<Select value={editing.priority} onChange={(event) => setEditing({ ...editing, priority: event.target.value as LocalSessionItem['priority'] })}>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><label>Статус<Select value={editing.status} onChange={(event) => setEditing({ ...editing, status: event.target.value as LocalSessionItem['status'] })}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label></div><label>Группа альтернатив<input value={editing.alternative} onChange={(event) => setEditing({ ...editing, alternative: event.target.value })} /></label><label>Заметка для этой сессии<textarea rows={3} value={editing.note} onChange={(event) => setEditing({ ...editing, note: event.target.value })} /></label><footer><Button tone="danger" onClick={() => { persist({ ...campaign, firstSessionItems: items.filter((item) => item.id !== editing.id), firstSessionFlows: flows.filter((entry) => entry.fromItemId !== editing.id && entry.toItemId !== editing.id) }); setEditing(null) }}>Убрать из сессии</Button><Button onClick={() => setEditing(null)}>Отмена</Button><Button variant="primary" onClick={() => { update(editing); setEditing(null) }}>Сохранить</Button></footer></Modal>}
    {flowEditor && <Modal title="Новый поток" close={() => setFlowEditor(false)}><div className="control-form__row"><label>От<Select value={flow.fromItemId} onChange={(event) => setFlow({ ...flow, fromItemId: event.target.value })}>{linked.map(({ item, entity }) => <option key={item.id} value={item.id}>{entity!.name}</option>)}</Select></label><label>К<Select value={flow.toItemId} onChange={(event) => setFlow({ ...flow, toItemId: event.target.value })}>{linked.map(({ item, entity }) => <option key={item.id} value={item.id}>{entity!.name}</option>)}</Select></label></div><label>Условие или выбор<textarea rows={3} value={flow.condition} onChange={(event) => setFlow({ ...flow, condition: event.target.value })} /></label><footer><Button onClick={() => setFlowEditor(false)}>Отмена</Button><Button variant="primary" disabled={!flow.fromItemId || !flow.toItemId || flow.fromItemId === flow.toItemId} onClick={addFlow}>Создать</Button></footer></Modal>}
  </section>
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(event) => { if (event.currentTarget === event.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2>{children}</section></div> }
