import { useState, type ReactNode } from 'react'
import { Badge, Button, EmptyState, Icon } from '../ds'
import type { LocalCampaignClock, LocalCampaignRecord, LocalCampaignSecret, LocalCampaignTask, LocalInboxItem } from '../fixtures/localCampaignCatalog'

type Props = { campaign: LocalCampaignRecord; persist: (next: LocalCampaignRecord) => void }
type Panel = 'clocks' | 'secrets' | 'tasks' | 'inbox'
const SECRET_STATUS: Record<LocalCampaignSecret['status'], string> = { hidden: 'Не раскрыт', partial: 'Частично', selected: 'Выбранным героям', everyone: 'Всем героям', disproved: 'Опровергнут', obsolete: 'Устарел' }
const CLOCK_KIND: Record<LocalCampaignClock['kind'], string> = { threat: 'Угроза', goal: 'Цель', project: 'Проект', world: 'Мир' }

export function LocalCampaignControlCenter({ campaign, persist }: Props) {
  const [panel, setPanel] = useState<Panel>('clocks')
  const [clockEditor, setClockEditor] = useState<LocalCampaignClock | 'new' | null>(null)
  const [clockDraft, setClockDraft] = useState<Omit<LocalCampaignClock, 'id' | 'history'>>({ title: '', kind: 'threat', value: 0, segments: 6, visibility: 'master', trigger: '' })
  const [secretEditor, setSecretEditor] = useState<LocalCampaignSecret | 'new' | null>(null)
  const [secretDraft, setSecretDraft] = useState<Omit<LocalCampaignSecret, 'id'>>({ title: '', truth: '', publicVersion: '', recipients: '', status: 'hidden' })
  const [taskText, setTaskText] = useState('')
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null)
  const [inboxText, setInboxText] = useState('')
  const [clockReasons, setClockReasons] = useState<Record<string, string>>({})

  const openClock = (clock: LocalCampaignClock | 'new') => { setClockEditor(clock); setClockDraft(clock === 'new' ? { title: '', kind: 'threat', value: 0, segments: 6, visibility: 'master', trigger: '' } : { title: clock.title, kind: clock.kind, value: clock.value, segments: clock.segments, visibility: clock.visibility, trigger: clock.trigger }) }
  const saveClock = () => { if (!clockDraft.title.trim()) return; const existing = clockEditor === 'new' ? null : clockEditor; const clock: LocalCampaignClock = { ...clockDraft, title: clockDraft.title.trim(), trigger: clockDraft.trigger.trim(), value: Math.min(clockDraft.value, clockDraft.segments), id: existing?.id ?? `clock-${crypto.randomUUID()}`, history: existing?.history ?? [] }; persist({ ...campaign, clocks: existing ? campaign.clocks.map((item) => item.id === clock.id ? clock : item) : [...campaign.clocks, clock] }); setClockEditor(null) }
  const moveClock = (clock: LocalCampaignClock, delta: number, reason: string) => { const value = Math.max(0, Math.min(clock.segments, clock.value + delta)); if (value === clock.value || !reason.trim()) return; const next = { ...clock, value, history: [...clock.history, { id: `change-${crypto.randomUUID()}`, delta, reason: reason.trim(), createdAt: new Date().toISOString() }] }; persist({ ...campaign, clocks: campaign.clocks.map((item) => item.id === clock.id ? next : item) }); setClockReasons({ ...clockReasons, [clock.id]: '' }) }
  const openSecret = (secret: LocalCampaignSecret | 'new') => { setSecretEditor(secret); setSecretDraft(secret === 'new' ? { title: '', truth: '', publicVersion: '', recipients: '', status: 'hidden' } : { title: secret.title, truth: secret.truth, publicVersion: secret.publicVersion, recipients: secret.recipients, status: secret.status }) }
  const saveSecret = () => { if (!secretDraft.title.trim() || !secretDraft.truth.trim()) return; const secret: LocalCampaignSecret = { ...secretDraft, title: secretDraft.title.trim(), truth: secretDraft.truth.trim(), publicVersion: secretDraft.publicVersion.trim(), recipients: secretDraft.recipients.trim(), id: secretEditor === 'new' ? `secret-${crypto.randomUUID()}` : secretEditor!.id }; persist({ ...campaign, secrets: secretEditor === 'new' ? [...campaign.secrets, secret] : campaign.secrets.map((item) => item.id === secret.id ? secret : item) }); setSecretEditor(null) }
  const saveTask = () => { if (!taskText.trim()) return; const tasks = editingTaskId ? campaign.tasks.map((item) => item.id === editingTaskId ? { ...item, text: taskText.trim() } : item) : [...campaign.tasks, { id: `task-${crypto.randomUUID()}`, text: taskText.trim(), source: 'masterboard' as const, done: false }]; persist({ ...campaign, tasks }); setTaskText(''); setEditingTaskId(null) }
  const addInbox = () => { const raw = inboxText.trim(); if (!raw) return; const tags = [...raw.matchAll(/#([\p{L}\p{N}_-]+)/gu)].map((match) => match[1].toLocaleLowerCase()); const item: LocalInboxItem = { id: `inbox-${crypto.randomUUID()}`, text: raw.replace(/#[\p{L}\p{N}_-]+/gu, '').trim(), tags, createdAt: new Date().toISOString() }; persist({ ...campaign, inbox: [...campaign.inbox, item] }); setInboxText('') }
  const consumeInbox = (item: LocalInboxItem, target: 'note' | 'task') => { persist({ ...campaign, inbox: campaign.inbox.filter((entry) => entry.id !== item.id), notes: target === 'note' ? [...campaign.notes, item.text] : campaign.notes, tasks: target === 'task' ? [...campaign.tasks, { id: `task-${crypto.randomUUID()}`, text: item.text, source: 'inbox', done: false }] : campaign.tasks }) }

  return <section className="campaign-section control-center"><header className="panel-heading"><div><span className="panel-kicker">Оперативный слой</span><h2>Пульт кампании</h2><p>Давление мира, закрытые знания и то, что мастеру нельзя потерять.</p></div><Badge tone="success" dot>Локально</Badge></header><nav className="control-center__tabs" aria-label="Разделы пульта">{([['clocks', 'Часы', campaign.clocks.length], ['secrets', 'Секреты', campaign.secrets.length], ['tasks', 'Задачи', campaign.tasks.filter((item) => !item.done).length], ['inbox', 'Входящие', campaign.inbox.length]] as const).map(([id, label, count]) => <button key={id} className={panel === id ? 'active' : ''} onClick={() => setPanel(id)}>{label}<span>{count}</span></button>)}</nav>
    {panel === 'clocks' && <Clocks clocks={campaign.clocks} reasons={clockReasons} setReason={(id, reason) => setClockReasons({ ...clockReasons, [id]: reason })} open={openClock} move={moveClock} remove={(id) => window.confirm('Удалить часы и историю изменений?') && persist({ ...campaign, clocks: campaign.clocks.filter((item) => item.id !== id) })} />}
    {panel === 'secrets' && <Secrets secrets={campaign.secrets} open={openSecret} remove={(id) => window.confirm('Удалить секрет?') && persist({ ...campaign, secrets: campaign.secrets.filter((item) => item.id !== id) })} />}
    {panel === 'tasks' && <Tasks tasks={campaign.tasks} text={taskText} editing={Boolean(editingTaskId)} setText={setTaskText} save={saveTask} edit={(task) => { setEditingTaskId(task.id); setTaskText(task.text) }} cancel={() => { setEditingTaskId(null); setTaskText('') }} toggle={(id) => persist({ ...campaign, tasks: campaign.tasks.map((item) => item.id === id ? { ...item, done: !item.done } : item) })} remove={(id) => persist({ ...campaign, tasks: campaign.tasks.filter((item) => item.id !== id) })} />}
    {panel === 'inbox' && <Inbox items={campaign.inbox} text={inboxText} setText={setInboxText} add={addInbox} consume={consumeInbox} remove={(id) => persist({ ...campaign, inbox: campaign.inbox.filter((item) => item.id !== id) })} />}
    {clockEditor && <Modal title={clockEditor === 'new' ? 'Новые часы' : 'Редактировать часы'} close={() => setClockEditor(null)}><label>Название<input autoFocus value={clockDraft.title} onChange={(event) => setClockDraft({ ...clockDraft, title: event.target.value })} /></label><div className="control-form__row"><label>Тип<select value={clockDraft.kind} onChange={(event) => setClockDraft({ ...clockDraft, kind: event.target.value as LocalCampaignClock['kind'] })}><option value="threat">Угроза</option><option value="goal">Прогресс цели</option><option value="project">Проект</option><option value="world">Состояние мира</option></select></label><label>Сегментов<select value={clockDraft.segments} onChange={(event) => setClockDraft({ ...clockDraft, segments: Number(event.target.value), value: Math.min(clockDraft.value, Number(event.target.value)) })}><option>4</option><option>6</option><option>8</option><option>10</option><option>12</option></select></label></div><label>Событие при заполнении<textarea rows={3} value={clockDraft.trigger} onChange={(event) => setClockDraft({ ...clockDraft, trigger: event.target.value })} /></label><label>Видимость<select value={clockDraft.visibility} onChange={(event) => setClockDraft({ ...clockDraft, visibility: event.target.value as LocalCampaignClock['visibility'] })}><option value="master">Только мастерам</option><option value="public">Можно показать игрокам</option></select></label><ModalActions close={() => setClockEditor(null)} save={saveClock} disabled={!clockDraft.title.trim()} /></Modal>}
    {secretEditor && <Modal title={secretEditor === 'new' ? 'Новый секрет' : 'Редактировать секрет'} close={() => setSecretEditor(null)}><label>Название<input autoFocus value={secretDraft.title} onChange={(event) => setSecretDraft({ ...secretDraft, title: event.target.value })} /></label><label>Мастерская истина<textarea rows={3} value={secretDraft.truth} onChange={(event) => setSecretDraft({ ...secretDraft, truth: event.target.value })} /></label><label>Публичная формулировка<textarea rows={3} value={secretDraft.publicVersion} placeholder="То, что можно сообщить игрокам" onChange={(event) => setSecretDraft({ ...secretDraft, publicVersion: event.target.value })} /></label><div className="control-form__row"><label>Состояние<select value={secretDraft.status} onChange={(event) => setSecretDraft({ ...secretDraft, status: event.target.value as LocalCampaignSecret['status'] })}>{Object.entries(SECRET_STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Кому известно<input value={secretDraft.recipients} placeholder="Все, группа, имена героев" onChange={(event) => setSecretDraft({ ...secretDraft, recipients: event.target.value })} /></label></div><ModalActions close={() => setSecretEditor(null)} save={saveSecret} disabled={!secretDraft.title.trim() || !secretDraft.truth.trim()} /></Modal>}
  </section>
}

function Clocks({ clocks, reasons, setReason, open, move, remove }: { clocks: LocalCampaignClock[]; reasons: Record<string, string>; setReason: (id: string, reason: string) => void; open: (clock: LocalCampaignClock | 'new') => void; move: (clock: LocalCampaignClock, delta: number, reason: string) => void; remove: (id: string) => void }) { return <div className="control-panel"><header><div><h3>Часы и угрозы</h3><p>Каждое движение сохраняет причину отдельной записью.</p></div><Button variant="primary" icon="plus" onClick={() => open('new')}>Новые часы</Button></header>{clocks.length ? <div className="clock-grid">{clocks.map((clock) => { const reason = reasons[clock.id] ?? ''; return <article key={clock.id} className={clock.value === clock.segments ? 'filled' : ''}><header><div><Badge tone={clock.kind === 'threat' ? 'warning' : 'neutral'}>{CLOCK_KIND[clock.kind]}</Badge><Badge tone={clock.visibility === 'public' ? 'success' : 'neutral'}>{clock.visibility === 'public' ? 'Для игроков' : 'Мастерское'}</Badge></div><Button size="sm" icon="pencil" aria-label={`Редактировать часы: ${clock.title}`} onClick={() => open(clock)} /></header><h4>{clock.title}</h4><div className="clock-track" aria-label={`${clock.value} из ${clock.segments}`}>{Array.from({ length: clock.segments }, (_, index) => <i key={index} className={index < clock.value ? 'active' : ''} />)}</div><strong>{clock.value} / {clock.segments}</strong><p>{clock.trigger || 'Событие при заполнении не задано.'}</p><input className="clock-reason" aria-label={`Причина движения: ${clock.title}`} value={reason} placeholder="Причина движения часов…" onChange={(event) => setReason(clock.id, event.target.value)} /><footer><Button size="sm" disabled={!clock.value || !reason.trim()} onClick={() => move(clock, -1, reason)}>− Откатить</Button><Button size="sm" variant="primary" disabled={clock.value === clock.segments || !reason.trim()} onClick={() => move(clock, 1, reason)}>+ Продвинуть</Button><Button size="sm" tone="danger" icon="trash-2" aria-label={`Удалить часы: ${clock.title}`} onClick={() => remove(clock.id)} /></footer>{clock.history.length > 0 && <details className="clock-history"><summary>История · {clock.history.length}</summary><ol>{[...clock.history].reverse().map((entry) => <li key={entry.id}><strong>{entry.delta > 0 ? `+${entry.delta}` : entry.delta}</strong><span>{entry.reason}</span><time>{new Date(entry.createdAt).toLocaleString('ru-RU', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}</time></li>)}</ol></details>}</article> })}</div> : <EmptyState icon="history" title="Часы ещё не заведены" hint="Создайте угрозу, проект или прогресс цели и двигайте его осознанными шагами." action={<Button variant="primary" icon="plus" onClick={() => open('new')}>Создать часы</Button>} />}</div> }
function Secrets({ secrets, open, remove }: { secrets: LocalCampaignSecret[]; open: (secret: LocalCampaignSecret | 'new') => void; remove: (id: string) => void }) { return <div className="control-panel"><header><div><h3>Секреты и знания</h3><p>Мастерская истина отделена от формулировки для игроков.</p></div><Button variant="primary" icon="plus" onClick={() => open('new')}>Новый секрет</Button></header>{secrets.length ? <div className="secret-list">{secrets.map((secret) => <article key={secret.id}><header><div><Badge tone={secret.status === 'hidden' ? 'warning' : secret.status === 'everyone' ? 'success' : 'neutral'}>{SECRET_STATUS[secret.status]}</Badge>{secret.recipients && <span>{secret.recipients}</span>}</div><div><Button size="sm" icon="pencil" aria-label={`Редактировать секрет: ${secret.title}`} onClick={() => open(secret)} /><Button size="sm" tone="danger" icon="trash-2" aria-label={`Удалить секрет: ${secret.title}`} onClick={() => remove(secret.id)} /></div></header><h4>{secret.title}</h4><dl><div><dt>Мастерская истина</dt><dd>{secret.truth}</dd></div><div><dt>Для игроков</dt><dd>{secret.publicVersion || 'Публичная формулировка не подготовлена.'}</dd></div></dl></article>)}</div> : <EmptyState icon="shield" title="Секретов пока нет" hint="Зафиксируйте истину ведущего отдельно от того, что знают герои." action={<Button variant="primary" icon="plus" onClick={() => open('new')}>Создать секрет</Button>} />}</div> }
function Tasks({ tasks, text, editing, setText, save, edit, cancel, toggle, remove }: { tasks: LocalCampaignTask[]; text: string; editing: boolean; setText: (value: string) => void; save: () => void; edit: (task: LocalCampaignTask) => void; cancel: () => void; toggle: (id: string) => void; remove: (id: string) => void }) { return <div className="control-panel"><header><div><h3>Задачи ведущего</h3><p>Короткий список подготовки с видимым источником.</p></div></header><div className="control-capture"><input value={text} placeholder="Что нужно подготовить…" onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') save() }} />{editing && <Button onClick={cancel}>Отмена</Button>}<Button variant="primary" icon={editing ? 'check' : 'plus'} disabled={!text.trim()} onClick={save}>{editing ? 'Сохранить' : 'Добавить'}</Button></div>{tasks.length ? <ol className="task-list">{tasks.map((task) => <li key={task.id} className={task.done ? 'done' : ''}><button aria-label={task.done ? `Вернуть задачу: ${task.text}` : `Выполнить задачу: ${task.text}`} onClick={() => toggle(task.id)}><Icon name={task.done ? 'check' : 'circle'} size={18} /></button><div><span>{task.text}</span><small>{task.source === 'inbox' ? 'Из входящих' : task.source === 'preparation' ? 'Подготовка' : 'Masterboard'}</small></div><div className="task-list__actions"><Button size="sm" icon="pencil" aria-label={`Редактировать задачу: ${task.text}`} onClick={() => edit(task)} /><Button size="sm" tone="danger" icon="trash-2" aria-label={`Удалить задачу: ${task.text}`} onClick={() => remove(task.id)} /></div></li>)}</ol> : <EmptyState icon="list-checks" title="Открытых задач нет" hint="Добавьте короткое действие подготовки или превратите входящую запись в задачу." />}</div> }
function Inbox({ items, text, setText, add, consume, remove }: { items: LocalInboxItem[]; text: string; setText: (value: string) => void; add: () => void; consume: (item: LocalInboxItem, target: 'note' | 'task') => void; remove: (id: string) => void }) { return <div className="control-panel"><header><div><h3>Входящие</h3><p>Быстрый захват без обязательной типизации. Теги можно писать через #.</p></div></header><div className="control-capture"><input value={text} placeholder="Мысль, имя, последствие… #тег" onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') add() }} /><Button variant="primary" icon="plus" disabled={!text.trim()} onClick={add}>Зафиксировать</Button></div>{items.length ? <ol className="inbox-list">{items.map((item) => <li key={item.id}><div><p>{item.text}</p><footer>{item.tags.map((tag) => <Badge size="sm" key={tag}>#{tag}</Badge>)}<time>{new Date(item.createdAt).toLocaleString('ru-RU', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}</time></footer></div><div><Button size="sm" onClick={() => consume(item, 'note')}>В заметку</Button><Button size="sm" onClick={() => consume(item, 'task')}>В задачу</Button><Button size="sm" tone="danger" icon="trash-2" aria-label={`Удалить входящую запись: ${item.text}`} onClick={() => remove(item.id)} /></div></li>)}</ol> : <EmptyState icon="scroll-text" title="Входящие разобраны" hint="Сюда можно быстро записать мысль, а тип определить позже." />}</div> }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="campaign-workspace__scrim" onMouseDown={(event) => { if (event.currentTarget === event.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><span className="panel-kicker">Пульт кампании</span><h2>{title}</h2>{children}</section></div> }
function ModalActions({ close, save, disabled }: { close: () => void; save: () => void; disabled: boolean }) { return <footer><Button onClick={close}>Отмена</Button><Button variant="primary" icon="check" disabled={disabled} onClick={save}>Сохранить</Button></footer> }
