import { useMemo, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Badge, Button, EmptyState, Icon, Select } from '../ds'
import type { LocalCampaignRecord, LocalSessionFlow, LocalSessionItem } from '../fixtures/localCampaignCatalog'
import { LocalThemeControl } from './LocalThemeControl'
import { useConfirm } from './useConfirm'

type Props = {
  campaign: LocalCampaignRecord
  persist: (campaign: LocalCampaignRecord) => void
  editSession: () => void
}

const PRIORITY: Record<LocalSessionItem['priority'], string> = { required: 'Обязательно', desired: 'Желательно', useful: 'Полезно', backup: 'Запас' }
const STATUS: Record<LocalSessionItem['status'], string> = { prepared: 'Подготовлено', current: 'Актуально', used: 'Использовано', skipped: 'Пропущено', moved: 'Перенесено', cancelled: 'Отменено' }

export function LocalSessionWorkspace({ campaign, persist, editSession }: Props) {
  const [tab, setTab] = useState<'plan' | 'library' | 'flows'>('plan')
  const [pickerOpen, setPickerOpen] = useState(false)
  const [editing, setEditing] = useState<LocalSessionItem | null>(null)
  const [flowOpen, setFlowOpen] = useState(false)
  const [draft, setDraft] = useState<Omit<LocalSessionItem, 'id' | 'entityId'>>({ role: '', priority: 'desired', status: 'prepared', alternative: '', note: '' })
  const [flowDraft, setFlowDraft] = useState<Omit<LocalSessionFlow, 'id'>>({ fromItemId: '', toItemId: '', condition: '' })
  const confirm = useConfirm()
  const attached = useMemo(() => campaign.firstSessionItems.map((item) => ({ item, entity: campaign.entities.find((entity) => entity.id === item.entityId) })).filter((row) => row.entity), [campaign])
  const available = campaign.entities.filter((entity) => !campaign.firstSessionItems.some((item) => item.entityId === entity.id))
  const itemName = (id: string) => attached.find((row) => row.item.id === id)?.entity?.name ?? 'Удалённый элемент'
  const attach = (entityId: string) => {
    const item: LocalSessionItem = { id: `session-item-${crypto.randomUUID()}`, entityId, role: '', priority: 'desired', status: 'prepared', alternative: '', note: '' }
    persist({ ...campaign, firstSessionItems: [...campaign.firstSessionItems, item], firstSessionStatus: 'draft' })
    setPickerOpen(false)
  }
  const saveItem = () => {
    if (!editing) return
    persist({ ...campaign, firstSessionItems: campaign.firstSessionItems.map((item) => item.id === editing.id ? { ...editing, ...draft } : item), firstSessionStatus: 'draft' })
    setEditing(null)
  }
  const removeItem = (item: LocalSessionItem) => confirm({ title: 'Убрать из сессии?', message: 'Объект останется в библиотеке. Удалятся только его привязка и переходы этой сессии.', confirmLabel: 'Убрать', cancelLabel: 'Отмена', onConfirm: () => persist({ ...campaign, firstSessionItems: campaign.firstSessionItems.filter((entry) => entry.id !== item.id), firstSessionFlows: campaign.firstSessionFlows.filter((flow) => flow.fromItemId !== item.id && flow.toItemId !== item.id) }) })
  const saveFlow = () => {
    if (!flowDraft.fromItemId || !flowDraft.toItemId || flowDraft.fromItemId === flowDraft.toItemId) return
    persist({ ...campaign, firstSessionFlows: [...campaign.firstSessionFlows, { ...flowDraft, id: `session-flow-${crypto.randomUUID()}` }] })
    setFlowOpen(false)
  }
  const prepared = Boolean(campaign.firstSessionObjective && campaign.firstSessionOpening && (campaign.firstSessionScenes.length || campaign.firstSessionItems.length))

  return <main className="target-dashboard created-dashboard session-workspace">
    <header className="local-dashboard-header"><div className="local-dashboard-header__utility"><Link to="/"><Icon name="arrow-left" size={16} /> Кампании</Link><strong>{campaign.name}</strong><div className="row"><Badge tone="neutral" dot>Локальные данные</Badge><LocalThemeControl /></div></div><nav className="local-dashboard-nav" aria-label="Разделы кампании"><Link to={`/local/campaign/${campaign.id}/overview`}><Icon name="layout-dashboard" size={16} /> Обзор</Link><Link className="active" to={`/local/campaign/${campaign.id}/session`}><Icon name="clapperboard" size={16} /> Сессия</Link><Link to={`/local/campaign/${campaign.id}/arcs`}><Icon name="waypoints" size={16} /> Сюжет</Link><Link to={`/local/campaign/${campaign.id}/control`}><Icon name="list-checks" size={16} /> Пульт</Link><Link to={`/local/campaign/${campaign.id}/library`}><Icon name="library" size={16} /> Библиотека</Link><Link to={`/local/campaign/${campaign.id}/map`}><Icon name="share-2" size={16} /> Связи</Link><Link to={`/local/campaign/${campaign.id}/world`}><Icon name="book-open" size={16} /> Заметки</Link></nav></header>
    <section className="session-workspace__heading"><div><span className="panel-kicker">Сессия 01 · {campaign.firstSessionStatus === 'ready' ? 'готова' : 'подготовка'}</span><h1>{campaign.firstSessionTitle}</h1><p>{campaign.firstSessionIdea || campaign.firstSessionObjective}</p></div><div className="session-workspace__heading-actions"><Badge tone={campaign.firstSessionStatus === 'ready' ? 'success' : 'warning'}>{campaign.firstSessionStatus === 'ready' ? 'Готова к игре' : 'Черновик'}</Badge><Button icon="pencil" onClick={editSession}>Паспорт</Button><Button variant="primary" icon="play" disabled={!prepared} onClick={() => persist({ ...campaign, firstSessionStatus: 'ready' })}>Подготовить к игре</Button></div></section>
    <dl className="session-passport"><div><dt>Ведущий</dt><dd>{campaign.firstSessionMaster || 'Не назначен'}</dd></div><div><dt>Время</dt><dd>{campaign.firstSessionInGameTime || 'Не задано'}</dd></div><div><dt>Арка</dt><dd>{campaign.storyArcs.find((arc) => arc.id === campaign.firstSessionArcId)?.title || 'Без арки'}</dd></div><div><dt>Старт</dt><dd>{campaign.firstSessionOpening || 'Не задан'}</dd></div></dl>
    <nav className="session-workspace__tabs" aria-label="Рабочие представления сессии">{([['plan', 'План', attached.length], ['library', 'Подборка', attached.length], ['flows', 'Потоки', campaign.firstSessionFlows.length]] as const).map(([id, label, count]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}<span>{count}</span></button>)}</nav>
    {tab === 'plan' && <section className="session-plan-grid"><article><div className="panel-heading"><div><span className="panel-kicker">Рабочая подборка</span><h2>Опорные элементы</h2></div><Button variant="primary" icon="plus" onClick={() => setPickerOpen(true)}>Из библиотеки</Button></div>{attached.length ? <ol>{attached.map(({ item, entity }, index) => <li key={item.id}><span>{String(index + 1).padStart(2, '0')}</span><div><div className="row"><Badge size="sm">{entity!.type}</Badge><Badge tone={item.priority === 'required' ? 'warning' : 'neutral'} size="sm">{PRIORITY[item.priority]}</Badge><Badge tone={item.status === 'used' ? 'success' : 'accent'} size="sm">{STATUS[item.status]}</Badge></div><h3>{entity!.name}</h3><p>{item.role || entity!.description || 'Роль в сессии не задана'}</p>{item.alternative && <small>Вариант: {item.alternative}</small>}</div><Button size="sm" icon="pencil" aria-label={`Настроить ${entity!.name}`} onClick={() => { setEditing(item); setDraft({ role: item.role, priority: item.priority, status: item.status, alternative: item.alternative, note: item.note }) }} /></li>)}</ol> : <EmptyState icon="library" title="Подборка сессии пуста" hint="Добавьте персонажей, места, секреты, материалы или другие объекты из библиотеки. Они останутся общими объектами кампании." action={<Button variant="primary" icon="plus" onClick={() => setPickerOpen(true)}>Выбрать из библиотеки</Button>} />}</article><aside><span className="panel-kicker">Цель</span><h2>{campaign.firstSessionObjective || 'Не сформулирована'}</h2><p>{campaign.firstSessionOpening || 'Стартовая ситуация не задана.'}</p><Link className="session-play-link" to={`/local/campaign/${campaign.id}/play`}>Открыть режиссёрский экран <Icon name="arrow-right" size={16} /></Link></aside></section>}
    {tab === 'library' && <section className="session-attached-grid">{attached.map(({ item, entity }) => <article key={item.id}><span className="panel-kicker">{entity!.type} · {PRIORITY[item.priority]}</span><h2>{entity!.name}</h2><p>{item.note || entity!.description || 'Заметка использования не добавлена.'}</p><footer><Button size="sm" icon="pencil" onClick={() => { setEditing(item); setDraft({ role: item.role, priority: item.priority, status: item.status, alternative: item.alternative, note: item.note }) }}>Настроить</Button><Button size="sm" tone="danger" icon="x" onClick={() => removeItem(item)}>Убрать</Button></footer></article>)}{!attached.length && <EmptyState icon="library" title="Нет связанных объектов" hint="Добавьте записи из библиотеки в план этой сессии." action={<Button variant="primary" onClick={() => setPickerOpen(true)}>Добавить</Button>} />}</section>}
    {tab === 'flows' && <section className="session-flows"><div className="panel-heading"><div><span className="panel-kicker">Условия и переходы</span><h2>Потоки сессии</h2><p>Связывайте опорные элементы без копирования карточек.</p></div><Button variant="primary" icon="plus" disabled={attached.length < 2} onClick={() => { setFlowDraft({ fromItemId: attached[0]?.item.id ?? '', toItemId: attached[1]?.item.id ?? '', condition: '' }); setFlowOpen(true) }}>Новый переход</Button></div>{campaign.firstSessionFlows.length ? <ol>{campaign.firstSessionFlows.map((flow) => <li key={flow.id}><strong>{itemName(flow.fromItemId)}</strong><span><Icon name="arrow-right" size={17} />{flow.condition || 'без условия'}</span><strong>{itemName(flow.toItemId)}</strong><Button size="sm" tone="danger" icon="trash-2" aria-label="Удалить переход" onClick={() => persist({ ...campaign, firstSessionFlows: campaign.firstSessionFlows.filter((item) => item.id !== flow.id) })} /></li>)}</ol> : <EmptyState icon="waypoints" title="Переходов пока нет" hint="Добавьте минимум два элемента и свяжите их условием, выбором или последовательностью." />}</section>}
    {pickerOpen && <Modal title="Добавить из библиотеки" close={() => setPickerOpen(false)}>{available.length ? <div className="session-picker">{available.map((entity) => <button key={entity.id} onClick={() => attach(entity.id)}><span className="panel-kicker">{entity.type}</span><strong>{entity.name}</strong><small>{entity.description || 'Без описания'}</small></button>)}</div> : <EmptyState icon="check" title="Вся библиотека уже в сессии" hint="Создайте новые объекты в библиотеке кампании." />}<footer><Button onClick={() => setPickerOpen(false)}>Закрыть</Button></footer></Modal>}
    {editing && <Modal title="Использование в сессии" close={() => setEditing(null)}><label>Роль в этой сессии<input value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value })} /></label><div className="control-form__row"><label>Приоритет<Select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as LocalSessionItem['priority'] })}>{Object.entries(PRIORITY).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><label>Фактический статус<Select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as LocalSessionItem['status'] })}>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label></div><label>Группа альтернатив<input value={draft.alternative} placeholder="Например: если герои идут через порт" onChange={(event) => setDraft({ ...draft, alternative: event.target.value })} /></label><label>Локальная заметка<textarea rows={4} value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} /></label><footer><Button onClick={() => setEditing(null)}>Отмена</Button><Button variant="primary" icon="check" onClick={saveItem}>Сохранить</Button></footer></Modal>}
    {flowOpen && <Modal title="Новый переход" close={() => setFlowOpen(false)}><div className="control-form__row"><label>Откуда<Select value={flowDraft.fromItemId} onChange={(event) => setFlowDraft({ ...flowDraft, fromItemId: event.target.value })}>{attached.map(({ item, entity }) => <option key={item.id} value={item.id}>{entity!.name}</option>)}</Select></label><label>Куда<Select value={flowDraft.toItemId} onChange={(event) => setFlowDraft({ ...flowDraft, toItemId: event.target.value })}>{attached.map(({ item, entity }) => <option key={item.id} value={item.id}>{entity!.name}</option>)}</Select></label></div><label>Условие или выбор<textarea rows={3} value={flowDraft.condition} placeholder="Если договор не заключён…" onChange={(event) => setFlowDraft({ ...flowDraft, condition: event.target.value })} /></label><footer><Button onClick={() => setFlowOpen(false)}>Отмена</Button><Button variant="primary" icon="check" disabled={!flowDraft.fromItemId || !flowDraft.toItemId || flowDraft.fromItemId === flowDraft.toItemId} onClick={saveFlow}>Создать</Button></footer></Modal>}
  </main>
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="campaign-workspace__scrim" onMouseDown={(event) => { if (event.currentTarget === event.target) close() }}><section className="campaign-workspace__modal" role="dialog" aria-modal="true" aria-label={title}><span className="panel-kicker">Сессия</span><h2>{title}</h2>{children}</section></div>
}
