import { Link } from 'react-router-dom'
import { Badge, Button, Icon, Select } from '../ds'
import type { LocalCampaignRecord, LocalSessionItem } from '../fixtures/localCampaignCatalog'

type Props = { campaign: LocalCampaignRecord; persist: (campaign: LocalCampaignRecord) => void; note: string; setNote: (value: string) => void; addNote: () => void; start: () => void }
const STATUS: Record<LocalSessionItem['status'], string> = { prepared: 'Подготовлено', current: 'Актуально', used: 'Использовано', skipped: 'Пропущено', moved: 'Перенесено', cancelled: 'Отменено' }

export function LocalLiveSessionWorkspace({ campaign, persist, note, setNote, addNote, start }: Props) {
  const attached = campaign.firstSessionItems.map((item) => ({ item, entity: campaign.entities.find((entity) => entity.id === item.entityId) })).filter((row) => row.entity)
  const updateStatus = (id: string, status: LocalSessionItem['status']) => persist({ ...campaign, firstSessionItems: campaign.firstSessionItems.map((item) => item.id === id ? { ...item, status } : item) })
  const itemName = (id: string) => attached.find((row) => row.item.id === id)?.entity?.name ?? 'Элемент'
  return <main className="local-session-shell live-workspace">
    <header className="local-session-topbar"><Link to={`/local/campaign/${campaign.id}/session`} className="row"><Icon name="arrow-left" size={16} /> План сессии</Link><Badge tone={campaign.firstSessionStatus === 'completed' ? 'neutral' : 'success'} dot>{campaign.firstSessionStatus === 'completed' ? 'Завершена' : campaign.firstSessionStatus === 'active' ? 'Идёт игра' : 'Готова'}</Badge></header>
    <section className="local-session-hero"><div><span className="panel-kicker">{campaign.name} · режиссёрский экран</span><h1>{campaign.firstSessionTitle}</h1><p>{campaign.firstSessionObjective}</p></div><div className="local-session-status"><span>Ответственный ведущий</span><strong>{campaign.firstSessionMaster || campaign.masters}</strong><small>{campaign.firstSessionInGameTime || campaign.activeTime}</small></div></section>
    {campaign.firstSessionStatus === 'ready' ? <section className="campaign-live-session__launch"><Icon name="clapperboard" size={28} /><h2>План готов к игре</h2><p>Статусы подборки, потоки и журнал останутся доступны во время проведения.</p><Button variant="primary" icon="play" onClick={start}>Начать сессию</Button></section> : <div className="live-workspace__grid">
      <section className="live-workspace__run"><div className="panel-heading"><div><span className="panel-kicker">Опорные элементы</span><h2>План в работе</h2></div><span className="panel-state">{attached.length}</span></div>{attached.map(({ item, entity }) => <article className={item.status === 'current' ? 'current' : ''} key={item.id}><div><div className="row"><Badge size="sm">{entity!.type}</Badge><Badge tone={item.priority === 'required' ? 'warning' : 'neutral'} size="sm">{item.priority}</Badge></div><h3>{entity!.name}</h3><p>{item.role || item.note || entity!.description}</p>{item.alternative && <small>Вариант: {item.alternative}</small>}</div>{campaign.firstSessionStatus !== 'completed' && <Select aria-label={`Статус ${entity!.name}`} value={item.status} onChange={(event) => updateStatus(item.id, event.target.value as LocalSessionItem['status'])}>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>}</article>)}{campaign.firstSessionFlows.length > 0 && <div className="live-workspace__flows"><span className="panel-kicker">Потоки</span>{campaign.firstSessionFlows.map((flow) => <p key={flow.id}><strong>{itemName(flow.fromItemId)}</strong><Icon name="arrow-right" size={15} /><span>{flow.condition || 'далее'}</span><Icon name="arrow-right" size={15} /><strong>{itemName(flow.toItemId)}</strong></p>)}</div>}</section>
      <aside className="live-workspace__log"><div className="panel-heading"><div><span className="panel-kicker">Фактическая запись</span><h2>Журнал</h2></div><span className="panel-state">{campaign.firstSessionLog.length}</span></div>{campaign.firstSessionStatus !== 'completed' && <div className="campaign-live-session__capture"><textarea rows={3} value={note} placeholder="Событие, последствие, новая сущность…" onChange={(event) => setNote(event.target.value)} /><Button variant="primary" icon="plus" disabled={!note.trim()} onClick={addNote}>Записать</Button></div>}<ol>{[...campaign.firstSessionLog].reverse().map((entry) => <li key={entry.id}><time>{new Date(entry.createdAt).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}</time><p>{entry.text}</p></li>)}</ol>{campaign.firstSessionStatus === 'active' && <Button block tone="danger" icon="check" onClick={() => persist({ ...campaign, firstSessionStatus: 'completed' })}>Завершить сессию</Button>}</aside>
    </div>}
  </main>
}
